### ISSUE TITLE
support when navbar changed and sidebar changed too?

### ISSUE THREAD

**Issue by mailbaoer** [QingWei-Li/docsify#100]
I have a lot of documents and i want navbar to change when the sidebar loads a different document .that supports?

**Comment by QingWei-Li** [comment]
Yes, you can. https://docsify.js.org/#/custom-navbar?id=markdown

**Comment by mailbaoer** [comment]
还有一点就是，sidebar的查找能不能优先查找父目录的_sidebar呢，我看目前是如果当前目录没有的话直接跑到了根目录，这样我就得把一个目录下面的子目录都放相同的sidebar了

**Comment by QingWei-Li** [comment]
额 其实我就是想要这样做的，看来我代码写错了
