### ISSUE TITLE
Search插件会去抓取name link的内容

### ISSUE THREAD

**Issue by woshiguabi** [QingWei-Li/docsify#102]
在Index目录和文档目录不一致时，这种情况可能不是想要的结果。

比如在MVC框架下我的访问路径是 //xxx/docs/index，文档目录可能是 //xxx/static/docs/，name link和访问路径一样，这时候就search插件就会去抓 /docs/index.md 这个文件，导致报错。

因为每个页面都有name link所以每次导航都会去抓，也就是点一下就会报一个错，看着不太舒服。

我现在的做法是在根路径下创建docs文件夹然后放个空的index.md文件，但是感觉这样做也不太好，有没有什么好的办法解决？

**Comment by QingWei-Li** [comment]
我也遇到这问题 但是一直没想到怎么回事，原来是 `nameLink` 😂

**Comment by woshiguabi** [comment]
😂😂😂
