### ISSUE TITLE
咱们的路由能像docpress那样不需要前面的#吗

### ISSUE THREAD

**Issue by mailbaoer** [QingWei-Li/docsify#120]
咱们的路由前面加个#总感觉别扭，还有就是id=后面加中文的话再chrome会被自动转义了，这个有办法处理吗

**Comment by QingWei-Li** [comment]
1. 路由除了直接写在 `index.html` 的 nav 里需要加 `#/`，其他地方都不用

*_sidebar.md*
```markdown
- Getting started
  - [Quick start](/quickstart)
  - [Writing more pages](/more-pages)
  - [Custom navbar](/custom-navbar)
  - [Cover page](/cover)

- Customization
  - [Configuration](/configuration)
  - [Themes](/themes)
  - [List of Plugins](/plugins)
  - [Write a Plugin](/write-a-plugin)
  - [Markdown configuration](/markdown)
  - [Language highlighting](/language-highlight)

- Guide
  - [Deploy](/deploy)
  - [Helpers](/helpers)
  - [Vue compatibility](/vue)
  - [CDN](/cdn)
  - [Offline Mode(PWA)](/pwa)

- [Changelog](/changelog)
```

2. 不进行 URL 编码的话，多数地方就无法识别链接，例如知乎、微信里
![image](https://cloud.githubusercontent.com/assets/7565692/23786448/1c22db68-05a8-11e7-953e-8195c74f2f99.png)

**Comment by mailbaoer** [comment]
恩，我明白，但是对整个路径来说最开始就有一个#了，就意味着所有的路径看起来最前面的都是#开头了。
第二个问题是因为我发现转义的路径用qq发出去之后，别人点击的时候前面的#也被转成%23了

**Comment by QingWei-Li** [comment]
关于第一个问题，抱歉我看错问题了。那个 `#/` 是为了实现单页应用（SPA）的功能，这样只需要一个 `index.html` 作为入口即可。
如果去掉的话也是可以（其实我这段时间正在做，用 HTML5 的 History API），这样的话就需要你部署到一个有权限配置代理的服务器，把所有路由都代理到 `/index.html` 上，参考[部署到 VPS](https://docsify.js.org/#/zh-cn/deploy?id=vps)。
本周末我会支持用 History API （也就是你能去掉 `#/`），同时你自己有服务器的话，就能实现你的需求

**Comment by mailbaoer** [comment]
嗯，明白了，非常感谢

**Comment by reverland** [comment]
如果需要在github上做这种html5 url跳转，可以看看我的博客用的方法。抄来的

**Comment by QingWei-Li** [comment]
@reverland 用的 `404.html`？最初版本的 docsify 也是用的这种方式 😂 但是不利于 SEO，所以后面又改成 hash router 了。但是现在要搞 SSR 又要兼容之前的方式 😂😂😂 现在正在重写 router 部分 😂

**Comment by reverland** [comment]
确实不利于SEO。。。所以怎么办

**Comment by QingWei-Li** [comment]
@reverland 搞 SSR 了，再往后或许可以提供编译静态文件（😂😂😂

**Comment by reverland** [comment]
又一个gitbook＝ ＝

**Comment by willin** [comment]
可以写个404.html 里通过js进行跳转
