### ISSUE TITLE
Discuss plugin

### ISSUE THREAD

**Issue by SuperAL** [QingWei-Li/docsify#123]
希望可以加入评论功能，但不知如何下手。
情况：使用了 docsify 在自己的服务器弄了个文档站点，希望可以在文档下方提供评论功能，不希望评论信息公开。

**Comment by nimojs** [comment]
安利一发 
http://nimojs.github.io/github-comments/

基于 github 的评论系统

让评论质量更高，让网站与 Github 关联 适合程序员的评论系统，基于 Github issues 留言

![](https://cloud.githubusercontent.com/assets/3949015/11060115/1892a24c-87d9-11e5-80a0-651c60f90875.png)

**Comment by alek13** [comment]
I think easiest way is to use https://disqus.com/ .
And maybe small plugin, that init it for you.
