### ISSUE TITLE
Strange dropdown list animation

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#13]
Hi, I have just updated to v0.6 and found this strange animation:
![](https://cloud.githubusercontent.com/assets/2010459/20712369/b1ba9d60-b67e-11e6-8ed8-711337bb58d1.gif)

Another thing is that the github corner widget is too large and has affected the navbar items:
![](https://cloud.githubusercontent.com/assets/2010459/20712546/6d71de56-b67f-11e6-8569-8f2cfcb18903.gif)

**Comment by liulex** [comment]
One more thing... I don't know if this is bug, though.
When refreshing the page, the text jumps:

![](https://cloud.githubusercontent.com/assets/2010459/20713596/da743716-b683-11e6-942c-29bff4166cab.gif)

**Comment by QingWei-Li** [comment]
The navbar in your `404.html` ?

**Comment by liulex** [comment]
No, it's in `_navbar.md`.

**Comment by QingWei-Li** [comment]
The animation is fixed. I'm not sure if the refresh problem is fixed 😅 Try the 0.6.1

**Comment by liulex** [comment]
I tried Chrome, Firefox and Edge, the animation is fine on Firefox and Edge, but still bad on Chrome...
The refresh problem still exists on all browsers...

**Comment by liulex** [comment]
Hmm.. I found another bug. On the navbar, the menu with a dropdown list has 15px font size, while those without dropdown lists are 16px.

**Comment by liulex** [comment]
The hovering animation is fine on Chrome now.

**Comment by liulex** [comment]
Oh, I found out that the refresh problem is due to the navbar in `404.html`. I thought when I have `data-load-navbar` enabled, the navbar in `404.html` will be ignored, so I didn't remove it.
After removing it, the problem disappears.

**Comment by QingWei-Li** [comment]
@liulex Can I add your documentation site into [the showcase](https://github.com/QingWei-Li/docsify#showcase)? It's great, I think it can help others as a reference. 😄

**Comment by liulex** [comment]
Sure! It's my pleasure.
I will also recommend your project in the changelog of my next update.
