### ISSUE TITLE
[Feature request] Embed files

### ISSUE THREAD

**Issue by noclat** [QingWei-Li/docsify#134]
I'd love to embed files in a document, just like [iA writer](https://ia.net/writer/) did with transclusion. Markdown and images would be imported as is, csv as tables, and other files as code blocks?

What do you think?

**Comment by jrappen** [comment]
I suggest:

```text
<!-- import: relative-link -->
```

**Comment by jrappen** [comment]
I found `madoko`:

* via npm
* <https://www.madoko.net>
* <https://github.com/koka-lang/madoko>
* <https://www.microsoft.com/en-us/research/video/madoko-a-scholarly-markdown>

You can:

* output static HTML
* output PDF
* include files
* style code in code blocks

**Comment by jrappen** [comment]
* <http://marked2app.com/help/Multi-File_Documents.html>
* <https://stackoverflow.com/questions/4779582/markdown-and-including-multiple-files>

**Comment by noclat** [comment]
Thanks! 💯
