### ISSUE TITLE
对多级目录的支持

### ISSUE THREAD

**Issue by wikilike7** [QingWei-Li/docsify#139]
你好：

请问对多级目录的支持如何，我在本地的预览是可以实现，但是上传至Github上就总是not found, 或者就是渲染的特别慢

我上传两张图片上来：

![image](https://cloud.githubusercontent.com/assets/3377226/24279510/264f2dd4-1085-11e7-895f-d92f359cdc4f.png)

![image](https://cloud.githubusercontent.com/assets/3377226/24279533/620197a4-1085-11e7-8668-3fc8fe7fe138.png)

**Comment by wikilike7** [comment]
我再补充下，在本地测试没问题，很奇怪的是传到Github上就not found，都快崩溃了....

截图1：本地的目录结构
![image](https://cloud.githubusercontent.com/assets/3377226/24285000/0b7234f6-10a9-11e7-8f7e-47848e43cb71.png)

截图2： 本地测试正常打开Outlook.md文件
![image](https://cloud.githubusercontent.com/assets/3377226/24285030/33bb3ed0-10a9-11e7-9106-a3261bc5c4e5.png)

截图3： Github上显示not found
![image](https://cloud.githubusercontent.com/assets/3377226/24285066/5ba0235c-10a9-11e7-9149-9394bfeefb7b.png)

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/zh-cn/configuration?id=base-path

你的根目录应该是 `/RECN-IT-FAQ/` 你没配置，那么访问 `/outlook.md` 肯定就 not found 了。要么你写成 `outlook` 用相对路径，要么配置 basePath

**Comment by wikilike7** [comment]
谢谢回复

很奇怪的问题，我重新建立了一个Reposity并且维持原有路径来访问，原来问题都没有了，Push到Github上也没有问题
