### ISSUE TITLE
能否增加菜单搜索？

### ISSUE THREAD

**Issue by meidea** [QingWei-Li/docsify#140]
搜索插件好像只能查询正文，能否把菜单名称也加入到匹配结果中？

**Comment by QingWei-Li** [comment]
是可以搜索到的
![image](https://cloud.githubusercontent.com/assets/7565692/24834603/589098ec-1d1d-11e7-90bf-231427ad803b.png)

**Comment by meidea** [comment]
![fa94d945-3a8a-4c54-88fd-4830d1f4d47f](https://cloud.githubusercontent.com/assets/19621448/24835977/a12759a4-1d42-11e7-99ff-41d2e5439600.png)
可能是中文的问题
