### ISSUE TITLE
侧边栏的 md 文件预览不出内部子标题

### ISSUE THREAD

**Issue by icorvoh** [QingWei-Li/docsify#141]
您好，感谢这个免费开源的在线电子书开源软件~

我用的是 Mac 下用 node 装的 docsify 3.3.1，我的 _sidebar.md 是这么写的

```
- [简介](README.md)
- [小全栈编程马拉松](intro-marathon.md)
- [关于作者](about-author.md)
```

其中为什么出现了如下图示的状况：左边侧边栏无法预览出当前 markdown 文件里的子标题？

![image](https://cloud.githubusercontent.com/assets/19285461/24441840/04c23cb2-148e-11e7-96c0-a7440ef47c0f.png)

我想达到官方文档上如下的效果，可以用 id 来绑定子标题，不知道该怎么做？

![image](https://cloud.githubusercontent.com/assets/19285461/24442080/062b0ea2-148f-11e7-8d27-b231c0da1a66.png)

感谢您的阅读和解答！

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/zh-cn/configuration?id=sub-max-level

**Comment by icorvoh** [comment]
哇哈哈，原来只需要轻松几步。。打扰了，谢谢啦~祝 docsify 越来越棒~

**Comment by wsyks** [comment]
我设置了subMaxLevel 为什么还是不能生成子目录呢
