### ISSUE TITLE
How to do anchor links within a single page

### ISSUE THREAD

**Issue by bojand** [QingWei-Li/docsify#142]
Hello, really enjoy docsify. Is there any way to be to have anchor links within a single page?

My use case is that I generate markdown API documentation automatically from JSDoc, and would like to be able to just add that as a single page within docsify project / site. The generated markdown automatically generates a "table of contents" that's a listing of all functions and classes of all the API within the project at the top of the file, and the table of contents links to the actual documentation for those that are elsewhere later in the file.

So for example it may end up being something like:

```markdown
<a href="#MyClass">MyClass</a>
...
<a name="MyClass"></a>
### MyClass
```
I can't seem to get this to work even if I try modifying the anchor links or setting `data-id` properties.

Is this possible to accomplish using docsify somehow (even with some hacking or manual manipulation of the generated markdown).

If not perhaps point me in the right direction and I can try and do a PR.

Thanks

**Comment by QingWei-Li** [comment]
You need generate markdown syntax. Such as
```md
[MyClass](#MyClass)
```

It will not be compiled if it is HTML.

**Comment by bojand** [comment]
Hmm maybe I didn't explain the issue correctly. It seems that docsify actually parses the file and sets the links to non-existent / invalid path. Lets say you have markdown file `api.md` and in it we have something like this:

```markdown
See documentation for [MyClass](#myclass)
```
And this should jump to elsewhere later in `api.md`. Docsify seems to create a link `http://localhost:3000/#/?id=myclass` when the _correct_ link is `http://localhost:3000/#/api?id=myclass`. I am trying to see if there is a workaround so it actually jump within the actual page, rather than trying to look for a path / route within docsify app. Hope this helps.

**Comment by QingWei-Li** [comment]
It really is a bug. Do you have time to fix it?

**Comment by bojand** [comment]
From some debugging it seems that this fixes it, but I am not sure about the complete effect my changes...?

```
function toURL (path, params) {
  var inline = path[0] === '#';
  var route = parse(replaceSlug(path));

  route.query = merge({}, route.query, params);
  path = route.path + stringifyQuery(route.query);
  path = path.replace(/\.md(\?)|\.md$/, '$1');

  if (inline) path = currentPath + path;

  return cleanPath('#/' + path)
}
```

Basically we detect that the path / href starts with `'#'` indicating usage of inline anchor / href link like

```markdown
[MyClass](#myclass)
```
It will generate a link `http://localhost:3000/#/api?id=myclass`
And then later in file if we have

```
<a name="MyClass" id="myclass"></a>
### MyClass
```

It will correctly link and jump to that anchor. Not sure if this is the correct approach.

**Comment by QingWei-Li** [comment]
Yes, I think it is right.

**Comment by trusktr** [comment]
It'd be neat to be able to apply this mapping to regular `<a>` tags too, because there are some cases where it is not possible to put the a`[]()` syntax.

For example, I want to make some tables, but GitHub-flavored markdown does not support cells with multi-line content, so I need to use `<table>` and due to the nesting, I can not place markdown inside the `<td>` elements. But I can only place `<a>` elements.
