### ISSUE TITLE
Markdown table rendering does not respect escaping of `|`

### ISSUE THREAD

**Issue by bojand** [QingWei-Li/docsify#144]
Hello, like I mentioned before I generate jsdoc to markdown. A standard way to specify multiple types allowed for a parameter is something like

```
* @param {String|Array} id the document id / key or an array of keys
```

which gets converted into markdown table like so:

```markdown
| Param | Type | Description |
| --- | --- | --- |
| id | <code>String</code> \| <code>Array</code> | the document id / key or an array of keys 
```

This is valid markdown and renders correctly:

| Param | Type | Description |
| --- | --- | --- |
| id | <code>String</code> \| <code>Array</code> | the document id / key or an array of keys 

With docsify it gets rendered as pictured:

![image](https://cloud.githubusercontent.com/assets/2081100/24676484/89fe11c4-1959-11e7-824c-853e5d805086.png)

The escaping `\|` is not respected it seems.

I'll try and dig into this some more.

**Comment by QingWei-Li** [comment]
This is marked bug, I think you should report a issue to [marked repo](https://github.com/chjj/marked).

**Comment by bojand** [comment]
Right wasn't sure if it was the markdown parser / renderer issue or docsify. There is already an [issue for this bug[(https://github.com/chjj/marked/issues/595). Although marked doesn't seem to be maintained according to issue (724)[https://github.com/chjj/marked/issues/724]. Others are suggesting using [markdown-it](https://github.com/markdown-it/markdown-it). 

A workaround is to use `&#124;` instead of `\|`.

**Comment by QingWei-Li** [comment]
`markdown-it` size is very big. I do not think it's a big problem. But you can custom markdown parser by `markdown` method https://docsify.js.org/#/markdown
