### ISSUE TITLE
why the documents can't open?

### ISSUE THREAD

**Issue by ihewro** [QingWei-Li/docsify#154]
today, when I open the static pages with using this project, I meet the error "not found".

not only my pages,but also the docsify https://docsify.js.org/ also can't load correctly.

I get confused. what's the error?

**Comment by ihewro** [comment]
中文:

所有用该项目构建的静态页面都无法打开，显示"not found".包括官方文档还有README.MD文档中的展示的文档都显示不了。

是什么错误呢？

**Comment by QingWei-Li** [comment]
Sorry, I'll fix it later. I'm on the way to work.
