### ISSUE TITLE
add a new markdown but did not generate sidebar

### ISSUE THREAD

**Issue by notedit** [QingWei-Li/docsify#157]
hi:

it is my first try docsify.   i try to add a guide.md in docs,  but docsify does not generate sidebar.

do i missing something?

the repo is in here  https://github.com/dotEngine/dotEngine-doc

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/zh-cn/more-pages?id=定制侧边栏

**Comment by notedit** [comment]
the doc says  it can generate.

"By default, the table of contents in the sidebar is automatically generated based on your markdown files"

**Comment by backspaces** [comment]
I agree with the idea presented here. 

I would like to give docsify a set of file names in my _sidebar.md, and have the sub-topics (H2's is the current default I think?) within each automatically generated for me.

Ex:
* [AgentScript](AgentScript.md)
* [Model Overview](ModelOverview.md)
.. should work exactly like the README.md does, auto generating the subtopics for the two files.

This may already be available?

It's quite a pain to do it by hand when we know it can be done for the default README.

Thanks for considering this.

**Comment by QingWei-Li** [comment]
All the rendering working is in the fly. No problem automatically generate sidebar.

**Comment by backspaces** [comment]
I found my problem. I mis-understood the way the H1-n defined the "level" in maxLevel and maxSubLevel. Problem solved. 

Now on to https://github.com/QingWei-Li/docsify/issues/203 where the path/*/dir/index.html is failing for me.

It would help me a lot if the configuration documentation could be expanded a bit. For one thing, my [foo](foo/bar?baz) links are getting modified (hash added) and I have no idea ho to turn it off. I want my .md files to be just plain .md and not messed with!
