### ISSUE TITLE
[question] Edit file button

### ISSUE THREAD

**Issue by Kikobeats** [QingWei-Li/docsify#162]
Hello!

I'm using docsify at [JS MythBusters](https://mythbusters.js.org/), thanks for the project, it looks amazing 😄.

One of my goals of the project is make easy people add more information.

Because every item of the table of contents is mapped with a markdown file, do you think that could be more or less easy add a "Edit file" button (like Wikipedia) and automatically create a PR associated with the project?

Maybe it could be written as a plugin.

**Comment by QingWei-Li** [comment]
Hi, @Kikobeats 
We can get the file path through the built-in method, so it's easy to implement. For example

```js
function(hook, vm) {
   const path = window.Docsify.route.parse().path
   console.log(vm.$getFile(path)) // such as `/README.md`
}
```
Do you want to submit a PR to implement it? 👻

**Comment by Kikobeats** [comment]
could be good idea place the html for the button and put the href using js?

**Comment by QingWei-Li** [comment]
We can insert html by hook function. See https://github.com/QingWei-Li/docsify/blob/master/docs/index.html#L56 and https://docsify.js.org/#/write-a-plugin

**Comment by QingWei-Li** [comment]
Hi, @Kikobeats 

I have added it to the doc, you can refer to this example.

```js
window.$docsify = {
  plugins: [
    function(hook, vm) {
      hook.beforeEach(function (html) {
        var url = 'https://github.com/QingWei-Li/docsify/blob/master' + vm.router.getFile()
        var editHtml = '[📝 EDIT DOCUMENT](' + url + ')\n'

        return editHtml
          + html
          + '\n----\n'
          + 'Last modified {docsify-updated} '
          + editHtml
      })
    }
  ]
}
```

**Comment by Kikobeats** [comment]
amazing, let me try it into mythbusters website, thanks!

**Comment by Kikobeats** [comment]
@QingWei-Li any idea how I can insert int after the first `h1` ?

**Comment by QingWei-Li** [comment]
Is it possible to use regular expression?

**Comment by Kikobeats** [comment]
@QingWei-Li sounds very weird
