### ISSUE TITLE
Duplicate "Edit page" entries in docs

### ISSUE THREAD

**Issue by jrappen** [QingWei-Li/docsify#166]
Visiting the docs:

<https://docsify.js.org>

shows duplicate "📝 EDIT DOCUMENT" links on any page:

* at the top
* at the bottom after the "last modified" timestamp

Compare:

<https://github.com/QingWei-Li/docsify/blob/ec887c1/docs/index.html#L59-L63>

---

Additionally I suggest writing "📝 Edit document" which is easier to read.

**Comment by QingWei-Li** [comment]
Hi,
I really want to show the edit button at the top and bottom, I do not think it's an issue.

**Comment by jrappen** [comment]
Not an issue, no. I wasn't sure this was intended.
