### ISSUE TITLE
Human readable formatUpdated

### ISSUE THREAD

**Issue by Kikobeats** [QingWei-Li/docsify#169]
I want to use a more human readable for `formatUpdated`

In particular, a formar similar to:

```
Monday, May 22nd 2017 (9d ago)
```

No problem If I have to load an external dependency for me user case, but in the plugin hook I didn't see avaiable the post timestamp.

**Comment by QingWei-Li** [comment]
You can handle the time manually.

```js
window.$docsify = {
  formatUpdated: function (time) {
    // ...

    return time
  }
}
```

**Comment by Kikobeats** [comment]
Thanks!

**Comment by Kikobeats** [comment]
@QingWei-Li  one thing, could be possible associate the timestamp with the last file modification? not just the last commit

**Comment by QingWei-Li** [comment]
I have no idea 🙁
