### ISSUE TITLE
多页的时候每页都有子标题，subMaxLevel和maxLevel 都设置了很大的值，但不会抓取文档中所有标题渲染成目录

### ISSUE THREAD

**Issue by fangsj** [QingWei-Li/docsify#171]
多页的时候每页都有子标题，我subMaxLevel和maxLevel 都设置了很大的值，左边的菜单不会显示每个页面的标题。
请问是我什么地方设置错误了么？
我的部分配置：
```js
window.$docsify = {
    name: '洛德API文档',
    repo: '',
    search: 'auto', // 默认值
    loadSidebar: true,
    maxLevel: 4,
    subMaxLevel: 4,
    coverpage: true,
    autoHeader: true,
    auto2top: true,
   search : [
     '/',            // => /README.md
     '/guide',       // => /guide.md
     '/get-started', // => /get-started.md
     '/zh-cn/',      // => /zh-cn/README.md
   ],
```
_sidebar:
```md
- 基础
 - [用户注册](/user)
 - [短信验证码]()
 - [定制导航栏](/guide)
 - [封面]()
```

我的“用户注册”文档类有一级标题，但是左侧目录没办法显示
你的https://docsify.now.sh/网站也有这样的问题。

**Comment by fangsj** [comment]
![1](https://cloud.githubusercontent.com/assets/8734881/26635785/720cbdec-464d-11e7-9932-6a3713d8cdfa.png)
![8aabec62-df8e-47f1-b2ab-deced6a32fd1](https://cloud.githubusercontent.com/assets/8734881/26635809/8611c58a-464d-11e7-80f6-f18c11f41d6d.png)

**Comment by fangsj** [comment]
![2](https://cloud.githubusercontent.com/assets/8734881/26636055/22ddca62-464e-11e7-9ede-42d6ac53bb2e.png)
![3](https://cloud.githubusercontent.com/assets/8734881/26636064/2cdebb2a-464e-11e7-98b6-5bc104b2366d.png)

**Comment by QingWei-Li** [comment]
修复在 4.1.9

**Comment by fangsj** [comment]
thank you very much!!!!!
