### ISSUE TITLE
可以支持本地直接打开么？

### ISSUE THREAD

**Issue by fangsj** [QingWei-Li/docsify#179]
我尝试了一下本地直接打开会报跨域问题！如果再网络情况不好的情况下，我想直接把这个文档copy给前端开发使用阅读
![image](https://cloud.githubusercontent.com/assets/8734881/26680164/d85cdaba-470a-11e7-808e-126a1136f368.png)

**Comment by fangsj** [comment]
我个人觉得检测到file:///协议的时候使用类似jsonp的这种传输协议，我个人建议哈！嘿嘿🙂

**Comment by fangsj** [comment]
我刚刚看到一个博客，说要支持编译静态文件,说的就是这个吧！支持你

**Comment by QingWei-Li** [comment]
Hi

这个报错是 Chrome 的安全策略决定的，我用 Safari 打开本地文件一切正常。推荐做法还是安装一个能启动静态文件服务器的工具，比如 [serve](//npm.im/serve)。

静态编译文件在这个 Issue 里有讨论 #136 我个人不喜欢静态编译，你可是使用 gitbook 等同类产品，或者你愿意的话可以来尝试实现下静态编译的功能 <3

**Comment by fangsj** [comment]
谢谢！个人觉得docsify 有些优点比gitbook更好，所以我更倾向于使用docsify。不过我也看了有许多人想使用静态编译的功能😆。回头研究一下，看看实现下。

**Comment by ideacco** [comment]
希望能增加静态编译的功能，这样就可以直接发文件包给别人了。
