### ISSUE TITLE
Deploying on vps

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#18]
Hi, as discussed in #7 , it's not SEO friendly to always return 404. From my understanding, it's due to the way github hosts the contents. Since I can also deploy the documention on my vps, I suppose there should be ways to avoid returning 404, is that right? If so, could you offer some instructions about it? Thanks!

**Comment by QingWei-Li** [comment]
You only need to proxy all requests to `index.html`

**Comment by liulex** [comment]
Thanks for your instructions! It helped a lot.

It works well for the pages in `/docs/`, but not for those in `/docs/zh-cn/`.
When `/zh-cn` is visited, docsify will try to use '/zh-cn.md'...

Adding one more location match can fix it:

	location = /zh-cn {
		rewrite / /zh-cn/ permanent;
	}


But this way a '/' will be appended to the url.
i.e. when I visit https://docs.snipaste.com/zh-cn, the url will be changed to https://docs.snipaste.com/zh-cn/.
Though it's no big deal, is there any way to fix this?

**Comment by QingWei-Li** [comment]
It is right. You need visited '/zh-cn/'.

**Comment by liulex** [comment]
OK. Thanks!
