### ISSUE TITLE
Does docsify support "next page"?

### ISSUE THREAD

**Issue by cyanzhong** [QingWei-Li/docsify#180]
Hi @QingWei-Li , I really like this project, it's very easy to use with clean/elegant UI.

I'm just wondering if docsify could provide something like `next page`.  (Or maybe we already have this?)

Think about you're using docsify generated website in mobile, due to screen size limitation, it's hard to navigate pages via side bar.

If you can provide an option, I think it would be great for mobile scenarios.

Anyway, thank you for your great work!

**Comment by jrappen** [comment]
Probably best way to implement this is via YAML frontmatter?

**Comment by QingWei-Li** [comment]
I just found out that @imyelo implemented a navigation plugin. https://github.com/imyelo/docsify-pagination

It's great, maybe it'll solve your problem.

@imyelo Can I include it in the docs?

**Comment by imyelo** [comment]
@QingWei-Li  Of course :wink:

**Comment by cyanzhong** [comment]
Let me try, thank you guys.

**Comment by marcelomrwin** [comment]
Thanks @imyelo and @QingWei-Li for the awesome job. Helpe me a lot.
