### ISSUE TITLE
分目录撰写sidebar加载错误

### ISSUE THREAD

**Issue by willin** [QingWei-Li/docsify#183]
<img width="611" alt="wx20170604-225709 2x" src="https://cloud.githubusercontent.com/assets/1890238/26762708/2f90da00-4979-11e7-9603-cc7f48a8cc96.png">

每次点击左侧菜单的链接都会加载一次页面和两次sidebar

```
loadSidebar: 'SUMMARY.md'
```

从gitbook迁移过来的项目

**Comment by QingWei-Li** [comment]
这是为了实现实现不同目录加载不同 sidebar 和 navbar 做的妥协，并不影响使用。其实你可以利用 alias 属性强制指定 `resource/SUMMARY.md` 从哪加载，例如

```js
window.$docsify = {
    alias: {
      '/basic/resource/SUMMARY.md': '/SUMMARY.md',
      '/resource/SUMMARY.md': '/SUMMARY.md'
    }
}
```

**Comment by willin** [comment]
可以使用通配符 * 吗

**Comment by QingWei-Li** [comment]
后面加上

**Comment by willin** [comment]
目前用:  https://leader.js.cool/#/basic/md/gitbook-to-docsify 可以解决该问题
