### ISSUE TITLE
Zoom plug-in issues

### ISSUE THREAD

**Issue by jrappen** [QingWei-Li/docsify#187]
* [ ] Zoom plug-in doesn't work on iOS on iPhone.
* [ ] Zoom plug-in works on badges. Maybe it would make sense to disable the zoom plug-in for all images that are links?
* [ ] When zooming into an image (that is not a link) and zooming back out, the zoom plug-in doesn't work anymore for that image on the page (but others) until page refresh.

**Comment by francoischalifour** [comment]
Hi @QingWei-Li, glad you're now using [medium-zoom](https://github.com/francoischalifour/medium-zoom). I noticed that you forgot to change the references in all [`plugins.md`](https://github.com/QingWei-Li/docsify/blob/fa772cfa94056e7f25b00d3f30a0c3604ae2d55e/docs/plugins.md#zoom-image) files though 😀

**Comment by jrappen** [comment]
Thanks to both of you!
