### ISSUE TITLE
Add context as CSS class

### ISSUE THREAD

**Issue by Kikobeats** [QingWei-Li/docsify#191]
For example, If we are at the follow URL:

```bash
http://localhost:3000/#/number/parse-string
```

attach the path as css  class in the body:

```html
<body class="number-parse-string ready sticky" cz-shortcut-listen="true">
</body>
```

This make easy add custom CSS for specific sections

Also could be added as `data-attribute`:

```html
<body class="ready sticky" data-page="parse-string" cz-shortcut-listen="true">
</body>
```

Related:

- https://themes.ghost.org/v1.0.0/docs/body_class

**Comment by Kikobeats** [comment]
awesome!

**Comment by QingWei-Li** [comment]
`v4.1.14` is released.
