### ISSUE TITLE
团队项目主页部署后，默认显示README.md，而不是index.html

### ISSUE THREAD

**Issue by airingursb** [QingWei-Li/docsify#192]
仓库名为[two-life/two-life.github.io](https://github.com/two-life/two-life.github.io)

部署之后 github 默认主分支部署，于是把docs内的页面都放进了root里

本地`docsify serve .` 后无问题，但是部署之后页面自动渲染 README.md 文件，删除 README.md 文件后，页面直接为null。

附上网址：
[https://two-life.github.io](https://two-life.github.io)

**Comment by QingWei-Li** [comment]
你试试加上 `.nojekyll`

**Comment by airingursb** [comment]
@QingWei-Li 

谢谢，加上`.nojekyll` 之后可以正常解析了！
