### ISSUE TITLE
Docs suddenly stopped working

### ISSUE THREAD

**Issue by Ehesp** [QingWei-Li/docsify#193]
Hello,

Our docs have stopped working all of a sudden. We haven't changed anything which would cause this so I wonder if it's a new release from the CDN.

http://invertase.io/react-native-firebase/

This shows our repos README, however going to http://invertase.io/react-native-firebase/docs/ shows the correct README for the docs, but no sidebar items.

Is this us, or something which has changed?

**Comment by QingWei-Li** [comment]
Have you changed the GitHub Pages configuration? You should choose the `/docs folder` in your case.

![image](https://user-images.githubusercontent.com/7565692/27109521-1b11d750-50d6-11e7-95ba-985b555fc3f2.png)

**Comment by chrisbianca** [comment]
@QingWei-Li The GitHub Pages configuration hasn't changed and is definitely pointing at the `/docs` folder.  I tried changing to `master ` then back to `/docs` to see if this would trick it into working but this hasn't changed anything

**Comment by QingWei-Li** [comment]
![image](https://user-images.githubusercontent.com/7565692/27118949-494e445c-5110-11e7-96b9-60e271f32b02.png)

It works for me. Maybe you should clean up browser cache.

**Comment by chrisbianca** [comment]
How strange. I've cleaned the cache, tried different browsers that have never viewed the page and even accessed through my phone network to check it wasn't some weird caching going on with my internet provider, but it's still displaying the wrong page for me.

Hopefully this will just fix itself over the next few hours...

**Comment by QingWei-Li** [comment]
So weird. I use [browserstack to test this site](https://www.browserstack.com/screenshots/38a72e5e07acaaf6c9f26def56ebd483160929ef), most of them are normal. Perhaps github itself bug?


![image](https://user-images.githubusercontent.com/7565692/27119712-7e40eed2-5113-11e7-8fc4-70ba7bfb1ece.png)

**Comment by Ehesp** [comment]
Yeah seems to be back to normal here, must have been Github... Sorry!
