### ISSUE TITLE
不启用docsify serve,直接访问index.html不能使用了么?

### ISSUE THREAD

**Issue by pumpinger** [QingWei-Li/docsify#196]
我记得以前是能使用的,这两天使用的时候发现不能自动引入README.md了.他的请求是
http://localhost:63342/test2/docs/index.html/README.md
不过影响也不大.

**Comment by QingWei-Li** [comment]
麻烦给个可复现的例子

**Comment by pumpinger** [comment]
不好意思没说清楚,
复现的步骤就是,所有css,js改成本地的之后,直接打开index.html.比如:file:///C:/workspace/php/test/docs/index.html#/
我用的是火狐,项目标题出现了,但是中间该读取的readme.md的内容显示的是"not found"

**Comment by QingWei-Li** [comment]
Chrome 和 FF 有安全策略禁止加载本地文件，所以没办法 也不推荐这么玩

**Comment by pumpinger** [comment]
Thx
