### ISSUE TITLE
markdown 脚注缺失

### ISSUE THREAD

**Issue by willin** [QingWei-Li/docsify#198]
![wx20170620-085053](https://user-images.githubusercontent.com/1890238/27311755-b175fdce-5528-11e7-9c27-be86d43f373a.png)

it's a bug.

**Comment by QingWei-Li** [comment]
footnote 在 marked 里并没有实现 https://github.com/chjj/marked/pull/351 你可以换一个 markdown parser

**Comment by kitaev-chen** [comment]
how to change a markdown parser in docsify?
