### ISSUE TITLE
即便翻墙了也打不开https://unpkg.com/docsify/themes/*

### ISSUE THREAD

**Issue by grt1st** [QingWei-Li/docsify#20]

**Comment by grt1st** [comment]
好吧，ss开全局模式打开了。但是在墙内打不开也就加载不了css/js，希望考虑一下这个问题

**Comment by QingWei-Li** [comment]
已经给 七牛的 staticfile 提 PR 了，合并后就可以使用 https://github.com/staticfile/static/pull/401
