### ISSUE TITLE
Init javascript on the page, after it has been loaded.

### ISSUE THREAD

**Issue by dobromir-hristov** [QingWei-Li/docsify#202]
Is there an event I can listen to on each page to init some small js i wrote? Now its initializing before the dom is parsed.

**Comment by Kikobeats** [comment]
I'm walking around the same issue, encaspulate the code into something like:

```js
window.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => {
      microlink('.demo-link', {
        rounded: true
      })
    }, 200)
  })
```

It's too tricky. Ideally, docsify could emit an event when the page is mounted:

```js
window.addEventListener('docsify:ready', () => {
      microlink('.demo-link', {
        rounded: true
      })
  })
```

**Comment by jhildenbiddle** [comment]
This can be accomplished using [docsify's plugin architecture](https://github.com/QingWei-Li/docsify/blob/master/docs/write-a-plugin.md):

```javascript
// Plugin
function doSomething(hook, vm) {
  hook.doneEach(function() {
    // Do something...
  });
}

// Add to plugin array
$docsify.plugins = [].concat(doSomething, $docsify.plugins);
```
