### ISSUE TITLE
support dynamic jsfiddle sample like element-ui doc

### ISSUE THREAD

**Issue by njleonzhang** [QingWei-Li/docsify#205]
```
::: demo
   code
:::
```
make this generate the online demo, so that we can embed sample code in document.

**Comment by QingWei-Li** [comment]
You can use vuep and handle it under its own to support code in markdown.

https://github.com/reverland/vud3/blob/master/docs/index.html#L32-L41
https://github.com/reverland/vud3/blob/master/docs/shape.md

**Comment by njleonzhang** [comment]
@QingWei-Li I am trying to make `element-ui` [demo-block](https://github.com/ElemeFE/element/blob/dev/examples/components/demo-block.vue) work with `docsify`. 

It almost works now. Please check this [sample](https://njleonzhang.github.io/vue-data-tables-doc/#/render-table) and its [source md](https://github.com/njleonzhang/vue-data-tables-doc/blob/master/render-table.md)

I just port element [demo-block](https://github.com/ElemeFE/element/blob/dev/examples/components/demo-block.vue) to a on-line version and config the `docsify` [index.html](https://github.com/njleonzhang/vue-data-tables-doc/blob/master/index.html) to make it work.

来中文吧。。
现在我遇到一个问题, 一旦`docsify`渲染了我的这个特殊的block以后，他就不继续渲染下面的内容了。
你可以看到这个demo的[source md](https://github.com/njleonzhang/vue-data-tables-doc/blob/master/render-table.md)里是这样写的

```
# Render a table
html
/*vue*/
<desc>
  测试描述
</desc>
<template>
  <div>Hello, {{ name }}!</div>
</template>

<script>
  export default {
    data() {
      return { name: 'Vue' }
    }
  }
</script>

# Render basic
```
但是最后生成的页面里Render basic没有生成，页面也没有报错，我觉得很奇怪，不知道和docsify有没有关系。请您帮忙看一下。
`docsify-demo-box`组件在[这里](https://github.com/njleonzhang/docsify-demo-box)

**Comment by QingWei-Li** [comment]
用 `vue.js` 而不是 `vue.min.js` 可以看到错误信息

**Comment by njleonzhang** [comment]
@QingWei-Li 。。。好的我看下

**Comment by njleonzhang** [comment]
还是没错误哎。

**Comment by QingWei-Li** [comment]
@njleonzhang 已提 PR

**Comment by njleonzhang** [comment]
感谢大神。。。最近android布局文件写多了，已经搞不清html标准了。我后面再改改，做得通用一点，不限于`vue`可以用。那样的话，前端的docsify文档，就可以用这个功能了。再次感谢。

**Comment by QingWei-Li** [comment]
Cool 可以做成 docsify 的插件

**Comment by njleonzhang** [comment]
恩，回头仔细看下plugin这块的文档，搞一个。搞不定再请教:)

**Comment by njleonzhang** [comment]
@QingWei-Li 先做了个plugin，目前只能支持Vue哦，

```
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="https://rawgit.com/njleonzhang/docsify-demo-box/master/dist/docsify-demo-box-plugin.js"></script>
```

```
window.$docsify = {
  ...

  plugins: [
    DemoBoxPlugin.create(jsResources, cssResources, bootCode)
  ]
}
```
这样就可以了。 [Doc](https://github.com/njleonzhang/docsify-demo-box)

**Comment by njleonzhang** [comment]
Hi 后来改动了下这个插件，现在依赖了marked和Prism，这个2个库是内置在docsify里面的，但是我这个plugin是改动docsify的plugin字段所以必须写在前面。（所以初始化的时候全局里并没有marked和Prism）
```
<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
```

目前我只能内置一份，不知道有没有办法用docsify里面的这2个库呢？

我尝试把plugin代码放在init hook里，然后发现整个直接是不work了
```

export let create = function(jsResources, cssResources, bootCode) {
  return function(hook, vm) {
    hook.init(function() {
      window.$docsify.markdown = {
        renderer: {
          code: function(code, lang) {
            if (/^\/\*\s*vue\s*\*\//.test(code)) {
              id++
              var DemoBlockWrapper = generateComponent(code, lang, jsResources, cssResources, bootCode)
              Vue.component('DemoBox' + id, DemoBlockWrapper)
              return '<' + 'demo-box-' + id + '></demo-box-' + id + '>'
            } else {
              lang = lang || ''
              var hl = Prism.highlight(code, Prism.languages[lang] || Prism.languages.markup)
              return '<pre v-pre data-lang="' + lang + '"><code class="lang-' + lang + '">' + hl + '</code></pre>'
            }
          }
        }
      }
    })
  }
}
```
