### ISSUE TITLE
侧边栏,如何自动生成目录

### ISSUE THREAD

**Issue by pumpinger** [QingWei-Li/docsify#212]
请问:
"定制侧边栏 默认情况下，侧边栏会根据当前文档的标题生成目录"
这句话的意思是 会根据doc 的markdown 的 "#"标题生成目录吗?
我的   loadSidebar  是 false,为什么没有生成目录咧~

demo:   https://pumpinger.github.io/xstarp/#/test.md

**Comment by pumpinger** [comment]
我想要的 就是 类似官网的    右边的内容滚动,左边侧边栏也会滚到相应的位置

**Comment by QingWei-Li** [comment]
设置 subMaxLevel 具体看文档

**Comment by pumpinger** [comment]
亲,我使用了 subMaxLevel , 左边也没有根据  标题生成目录呀~
![image](https://user-images.githubusercontent.com/10737255/28403178-21538072-6d56-11e7-9ece-baef5fd0d370.png)
