### ISSUE TITLE
The "check box" style issue !

### ISSUE THREAD

**Issue by paulwan** [QingWei-Li/docsify#215]
![screen shot 2017-07-18 at 3 50 28 pm](https://user-images.githubusercontent.com/2821581/28306190-f58479dc-6bd0-11e7-8d12-6ca5bfed2b8d.png)
<img width="68" alt="screen shot 2017-07-18 at 3 50 44 pm" src="https://user-images.githubusercontent.com/2821581/28306189-f566dff8-6bd0-11e7-86e3-543a5b1f4482.png">
Can I set on "Check-box" style in docsify's markdown file ( "[x]") like the second image ?

**Comment by QingWei-Li** [comment]
`marked` does not support Github task lists. https://github.com/chjj/marked/pull/587
But I think I can simply implement this feature.

**Comment by iolaizola** [comment]
I tested it on Chrome and Firefox.
Even if it properly works in Chrome, bullets are not removed in Firefox renders. (Firefox v57.0)
