### ISSUE TITLE
Load _sidebar.md only if file exists.

### ISSUE THREAD

**Issue by truetamtam** [QingWei-Li/docsify#218]
Could it be a better option, to load _sidebar.md only if file(_sidebar.md) exists?

Case:
|-root
|-_sidebar.md (**here is navigation from _sidebar.md**)
|--/API folder/
&nbsp;&nbsp;|- API.md
&nbsp;&nbsp;|-{ **no _sidebar.md** } (**here docsify handles sidebar navigation from markdown**)

**Comment by QingWei-Li** [comment]
No way to automatically judge, but you can configure `alias`

```js
window.$docsify = {
  alias: {
    '/.*/_sidebar.md': '_sidebar.md'
  }
}
```

Example: https://github.com/ElemeFE/vue-amap/blob/dev/src/docs/index.html#L24
