### ISSUE TITLE
为什么我把docsify项目放在后端项目中的静态资源文件夹下，index页面读取侧边栏配置文件是 index.html/_sidebar.md

### ISSUE THREAD

**Issue by SuperAL** [QingWei-Li/docsify#222]
如题，我把整个项目放在一个存在后端语言的项目中，放于静态资源文件夹下，直接通过访问静态资源的方式 `http://domain/static/docs/index.html` 来访问 docsify 页面，它默认读取侧边栏配置的地址是 `http://domain/static/docs/index.html/_sidebar.md`，为什么不是默认读取同级目录下的配置文件呢？

最后我通过配置 `basePath: '../'` 解决了这个问题。

**Comment by QingWei-Li** [comment]
直接访问 `http://domain/static/docs/`
