### ISSUE TITLE
为什么无法正常使用search功能呢？

### ISSUE THREAD

**Issue by ihewro** [QingWei-Li/docsify#223]
1. 我的文档本地目录是这样的：

![_ _20170726030559](https://user-images.githubusercontent.com/20165605/28589130-6316d722-71af-11e7-8002-9c7d43af09e3.png)

2. 我在index.html添加的js为：

![_ _20170726030814](https://user-images.githubusercontent.com/20165605/28589209-be1d0204-71af-11e7-88ba-b82cb65a1969.png)

3. 下面也引入了search插件必须的代码
```html
<script src="//cdn.jsdelivr.net/npm/docsify@latest/lib/plugins/search.min.js"></script>
```

可是仍然无法正常使用搜索功能，求解？

文档源码地址：<https://coding.net/u/ihewro/p/typecho-theme-tea-docs/git>
文档演示：<https://handsome.ihewro.com>

希望能够得到指点，感激不尽

**Comment by QingWei-Li** [comment]
出啥问题。我这边正常的
![image](https://user-images.githubusercontent.com/7565692/28598965-b36379f4-71d9-11e7-92f5-b3ced44506a2.png)

**Comment by ihewro** [comment]
@QingWei-Li  感谢回复！

但是它只能搜索**首页**的内容（homepage: 'home.md'）

比如搜索“插件”，plugin.md有相关关键字，却无法搜索到
![_ _20170726081437](https://user-images.githubusercontent.com/20165605/28599111-bb3e838e-71da-11e7-8220-af7b8a9e3894.png)

**Comment by QingWei-Li** [comment]
之前只能搜索 2 级标题，现在增加了一个参数可以搜索 1 - 6 级标题

```js
{
  search: {
    depth: 6
  }
}
```

**Comment by ihewro** [comment]
很棒！终于解决了！

**Comment by hamger** [comment]
我设置了 depth：6 但是依然没有效果

**Comment by chenhongen** [comment]
> 我设置了 depth：6 但是依然没有效果

解决了吗？我也没效果。。

**Comment by xieerduos** [comment]
> 很棒！终于解决了！

说方案，你怎么解决的

**Comment by zhengjinhuai** [comment]
把search配置中的paths去掉就可以了

**Comment by xiaopan369** [comment]
> 把search配置中的paths去掉就可以了
感谢可以了
