### ISSUE TITLE
添加了.nojekyll文件，但是码云上部署访问时还是提示找不到_sidebar.md、_navbar.md

### ISSUE THREAD

**Issue by lamtsui0620** [QingWei-Li/docsify#227]
添加了.nojekyll文件，但是码云上部署访问时还是提示找不到_sidebar.md、_navbar.md，请问下是什么原因？
![pb qfqu qnn3aazbv1 p](https://user-images.githubusercontent.com/8268287/28957740-e0c2f976-7925-11e7-9d97-722cd1fb9ead.png)
![72g p1 ig g1s jn7gxc](https://user-images.githubusercontent.com/8268287/28957742-e2412a66-7925-11e7-8c92-c1dae40648b3.png)

**Comment by QingWei-Li** [comment]
没用过码云，你只要确保部署上去那个路径下有这个文件就对了，这不是 docsify 的问题

**Comment by lamtsui0620** [comment]
有的 和index.html是同一个目录路径

________________________________

**Comment by QingWei-Li** [comment]
链接可以公开么，发我看下

**Comment by lamtsui0620** [comment]
后面咨询了下码云pages的管理员，码云的pages是基于jekyll的，添加_config.yml文件，将要忽略的文件配置进去就好，但是一开始创建的时候.nojekyll是可以的，.nojekyll是将项目部识别为jekyll？

2017-08-04 18:16 GMT+08:00 cinwell.li <notifications@github.com>:

**Comment by QingWei-Li** [comment]
GitHub 直接添加 `.nojekyll` 就好了

**Comment by lamtsui0620** [comment]
嗯嗯，可能是github和码云的机制不太一样吧。
对了，我根据 https://docsify.js.org/#/zh-cn/ssr
，想在ubuntu上实现通过ip或者地址直接去渲染访问git上的代码，一直都不成功

2017-08-07 11:27 GMT+08:00 cinwell.li <notifications@github.com>:

**Comment by lamtsui0620** [comment]
我也将你那个例子放上去，也不成功

在 2017年8月7日 上午11:32，Lam Tsui <twtssofn2237@gmail.com>写道：

**Comment by QingWei-Li** [comment]
查下日志吧，没日志我也不知道啥情况。肯定是可以跑的

**Comment by lamtsui0620** [comment]
[image: 内嵌图片 1]
其实是用哪个命令启动？

2017-08-07 11:35 GMT+08:00 cinwell.li <notifications@github.com>:

**Comment by lamtsui0620** [comment]
[image: 内嵌图片 1]
npm run deploy

2017-08-07 12:40 GMT+08:00 Lam Tsui <twtssofn2237@gmail.com>:

**Comment by lamtsui0620** [comment]
[image: 内嵌图片 1]

2017-08-07 12:43 GMT+08:00 Lam Tsui <twtssofn2237@gmail.com>:

**Comment by QingWei-Li** [comment]
啥都没有 😂
![image](https://user-images.githubusercontent.com/7565692/29013414-8c0f330c-7b75-11e7-839d-40d7ba4b2876.png)

**Comment by lamtsui0620** [comment]
​

2017-08-07 13:37 GMT+08:00 cinwell.li <notifications@github.com>:

**Comment by yzhang921** [comment]
@lamtsui0620 最后这个配置怎么解决的啊，GitHub国内没有梯子的小白用户访问比较慢，页面里面包含了图表和gif之后更加难受，还是有必要在码云也部署一份

**Comment by yzhang921** [comment]
添加 _config.yml 加入
```yaml
include: [_navbar.md]
```
