### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by seeyou404** [QingWei-Li/docsify#23]
![0](https://cloud.githubusercontent.com/assets/12776545/21038805/c0a7746e-be13-11e6-9567-6d74b6fe0c4f.png)
这个是我通过docsify-cli生成的基本的结构，按照文档上说的做多页面的形式，目录结构如下：
![1](https://cloud.githubusercontent.com/assets/12776545/21038821/d9a52858-be13-11e6-9c75-4b2170371255.png)
但是当我点击 *guide*的时候，*url*是*localhost:3000/guide*，但是页面为空白。通过控制台发现请求的路径是:*localhost:3000/guide/README.md*。所以把目录变成下面这样：
![2](https://cloud.githubusercontent.com/assets/12776545/21038874/3cadc568-be14-11e6-8d43-4a3ae28c3ade.png)
*guide*文件也是能正常访问的。为何和文档上说的不一样，是我的写法不对吗？？

**Comment by QingWei-Li** [comment]
应该写成 `/guide` 而不是 `/guide/`，你点击链接跳转到其实是后者。前者请求的文件才是 `/guide.md`

**Comment by seeyou404** [comment]
不行的，按照你上面的做法会出现如下的错误：`docsify.js:2477 Uncaught TypeError: Cannot read property '1' of null(…)`，因为`basePath = basePath.match(/(\S+\/)[^\/]+$/)[1]`这个正则匹配不出任何东西。改成这样`basePath = basePath.match(/(\S*\/)[^\/]+$/)[1]`就能按照你上面所说的正常运行了。

**Comment by QingWei-Li** [comment]
哦 那我晚上修下
