### ISSUE TITLE
noCompileLinks doesn't work with ../

### ISSUE THREAD

**Issue by nitzantomer** [QingWei-Li/docsify#230]
I have nested directories in my docsify based site, that is the structure is something like this:
- root
  - index.html
  - _sidebar.md
  - README.md
  - sub1
    - index.html
    - _sidebar.md
    - README.md
    - sub1.2
      - index.html
      - _sidebar.md
      - README.md
  - sub2
    - index.html
    - _sidebar.md
    - README.md

Everything works perfectly, except that in sub-directories, in the `_sidebar.md` files I try to link to documents in parent directories, like so:
```markdown
- [Getting started](../)
...
```

But the links are compiled into: `#/..`  
I tried using the `noCompileLinks` feature:
```javascript
window.$docsify = {
    noCompileLinks: [
        "../*"
    ]
}
```
But it has no effect.

Any idea how to solve this?  
Thanks.

**Comment by QingWei-Li** [comment]
You need to use regular expression: `../.*` It will be executed by `new RegExp('../.*')`

**Comment by nitzantomer** [comment]
Oh, makes sense.

Also, now that it works I notice that it opens it in a new tab, is there a way to keep it in the same window?  
I know that I can control it with `external-link-target`, but I do have some external links which I'd like to open in a new tab, but in this case, I just don't consider it as an "external link".

Thanks.

**Comment by QingWei-Li** [comment]
Now you can set the link attribute separately


```md
[link](/demo ":target=_blank")
[link](/demo2 ":target=_self")
```

**Comment by nitzantomer** [comment]
Works like a charm.
Thanks a lot for this product.
