### ISSUE TITLE
左侧菜单导航，定位错乱

### ISSUE THREAD

**Issue by xuxueli** [QingWei-Li/docsify#234]
你好，我在使用docsify的过程，侧边栏菜单点击之后，定位和高亮产生错乱，还望可以给些建议，谢谢。

问题重现：进入以下链接，点击侧边栏菜单 “一、简介”，但是高亮的侧边栏章节却是 “1.2 特性”，点击和高亮无法保持一致，产生错乱。（只有在设置 “coverpage: false” 的时候才会正常）

地址：http://www.xuxueli.com/xxl-job/#/?id=%e4%b8%80%e3%80%81%e7%ae%80%e4%bb%8b

**Comment by Binaryify** [comment]
何时能修复这个 bug, 困扰挺久的

**Comment by QingWei-Li** [comment]
@Binaryify @xuxueli 请使用最新版

**Comment by Binaryify** [comment]
@QingWei-Li 
问题依然
https://binaryify.github.io/NeteaseCloudMusicApi/#/

**Comment by QingWei-Li** [comment]
@Binaryify @xuxueli `4.3.4` 已修复

**Comment by Binaryify** [comment]
@QingWei-Li 
是的,正常了,感谢修复

**Comment by xuxueli** [comment]
@QingWei-Li 
非常感谢，问题已修复！

**Comment by fy0** [comment]
@QingWei-Li 这个问题还是存在，你试试点上面那文档左侧的“安装” “运行” “接口文档”

当下是对的，但是scroll结束后高亮会跳一下刷到页面中最后一个菜单标签，然后就错了。
