### ISSUE TITLE
Privacy error with custom subdomain and github pages

### ISSUE THREAD

**Issue by rentrop** [QingWei-Li/docsify#236]
Hi everyone,

thanks for the great work you do with docsify.

Trying to host my docsify website on github (https://github.com/sapaso/sapaso.github.io) with the custom subdomain http://docs.sapaso.de results in

> Your connection is not private

When hosting it "without" a custom subdomain on https:/sapaso.github.io it worked.

Following [this](https://help.github.com/articles/setting-up-a-custom-subdomain/) tutorial on how to setup a CNAME with a custom subdomain, using `dig` i get

```
dig docs.sapaso.de +nostats +nocomments +nocmd

; <<>> DiG 9.8.3-P1 <<>> docs.sapaso.de +nostats +nocomments +nocmd
;; global options: +cmd
;docs.sapaso.de.			IN	A
docs.sapaso.de.		3599	IN	CNAME	sapaso.github.io.
sapaso.github.io.	3599	IN	CNAME	sni.github.map.fastly.net.
sni.github.map.fastly.net. 23	IN	A	151.101.1.147
sni.github.map.fastly.net. 23	IN	A	151.101.65.147
sni.github.map.fastly.net. 23	IN	A	151.101.129.147
sni.github.map.fastly.net. 23	IN	A	151.101.193.147
```

Any ideas on how to fix this?

**Comment by fgallaire** [comment]
https://help.github.com/articles/securing-your-github-pages-site-with-https/
"HTTPS is not supported for GitHub Pages using custom domains."

But seems you can do it with some DNS services:
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by alek13** [comment]
I think we can close this issue, since its not Docsify's issue.
@fgallaire gives a workaround link, but I think its not so really needed to use the `https` instead `http`

**Comment by nateGeorge** [comment]
It should work now.  Notice you need to remove and readd your custom domain after changing the A records and setting the settings to use HTTPS: https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

**Comment by priteshusadadiya** [comment]
I am having the same issue.I created the www sub-domain and and added to my repo -> settings -> custom domain name

on DNS server added A records 
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

and i am receiving the privacy errors on https://www.priteshusadadiya.com and i am also not able to check "Lets Encrypt" checkbox on settings page.

Any idea how to solve this ?

**Comment by mayandhelder** [comment]
@priteshusadadiya how did you solve it?

**Comment by priteshusadadiya** [comment]
there was a issue with my DNS Configuration.

I was redirecting the www sub domain to apex (main). to fix this just change your dns record to yourusername.github.io 

wait for couple of minutes and go to github project -> settings and save changes again for domain field.
"Lets Encrypt" checkbox will get enabled. **check it**

and you are done.

**It might take around 48 hours for Github to generate HTTPS certificate on custom domain so, you might want to wait for it.**

**Comment by mayandhelder** [comment]
Thank you @priteshusadadiya . it works now!
