### ISSUE TITLE
Problems in page navigation

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#24]
For example:
1. Open https://docs.snipaste.com/
1. Click 'Image Edit'
   * Problem 1: the page does not jump to `#image-edit`
1. Scroll the current page, then click 'Image Edit' again, **no effects**
1. But if we now click 'Snip' or 'Paste', the page jumps correctly
   * Problem 2: however, in the sidebar, the highlighted menu is still "Image Edit'
1. Then click on another top-level page in the sidebar, for exmaple, 'Advanced Configs'
   * Problem 3: the page is not scrolled to top

**Comment by liulex** [comment]
Thanks for the update! It solved the first two problems, but the third seems not fixed...
Maybe it's intended? Because keeping the scrollbar position is good for single page sites like https://docsify.js.org/.
But for multi-page sites,I think it would be better to scroll to top when jumping to another page, or at least an option should be provided.

Or, maybe you could automatically insert an invisible element at the top of each page, with an id like "top"? So that I can append `#top` to the link to make it scroll to top.

Thansk for your work. :smile:

**Comment by QingWei-Li** [comment]
Sorry to miss the Problem 3.

I will add a option to automatically scroll to top in 1.1

**Comment by liulex** [comment]
Great! Thanks.

**Comment by liulex** [comment]
Another similar problem:
**Chinese** ids on the custom sidebar has no effect on mobile browsers. Tested on Firefox for Android.

**Comment by QingWei-Li** [comment]
> Chinese ids on the custom sidebar has no effect on mobile browsers. Tested on Firefox for Android.

Fixed in `1.1.4`

**Comment by liulex** [comment]
@QingWei-Li Thanks!

**Comment by whyboris** [comment]
I think the solution is in the `window.$docsify` object, but I can't seem to get it to work:
https://docsify.js.org/#/configuration?id=auto2top
