### ISSUE TITLE
Expected ';' on line 3131

### ISSUE THREAD

**Issue by C-Lodder** [QingWei-Li/docsify#240]
on IE11, there appears to be an error coming from line **3131**:

> Expected ';'

You're also getting the same error on your own Docs page:

### Testing instructions:

- Go to: https://docsify.js.org/#/?id=docsify
- On the sidebar, click the `Themes` menu item

**Comment by QingWei-Li** [comment]
Please use the latest version

**Comment by C-Lodder** [comment]
@QingWei-Li We were using the latest version at the time and we're using the latest version now. The error is still there.

There's also another error when you click on the "Get Started" button:

![screeny](https://user-images.githubusercontent.com/2019801/30207718-53588d66-9488-11e7-8696-641ef58af428.png)

**Comment by C-Lodder** [comment]
If a PR gets submitted, I'll be more than happy to test. Just ping me

**Comment by QingWei-Li** [comment]
Okay, It would be better if you could help solve it. Thanks.

**Comment by C-Lodder** [comment]
Apologies. It wasn't docsify's issue.

```
window.__EXECUTE_RESULT__ = new Function(code);
```

The JS being injected into `new Funtion()` was missing some semi-colons
