### ISSUE TITLE
Navi highlighting is not working properly when the content of [id] pointed to is short

### ISSUE THREAD

**Issue by ihipop** [QingWei-Li/docsify#241]
Demo form official `docsify`  doc https://docsify.js.org/#/more-pages?id=ignoring-subheaders

![image](https://user-images.githubusercontent.com/423077/29801977-1e8b5ae0-8ca5-11e7-9c78-2286f23004e4.png)

**Comment by fy0** [comment]
@ihipop Hi, I meet same problem and fixed it.

https://github.com/QingWei-Li/docsify/pull/242
