### ISSUE TITLE
bug with special header?

### ISSUE THREAD

**Issue by iromise** [QingWei-Li/docsify#256]
I am using some relative path  to  show picture in typora(a markdown editor) as follows, but the online docsify cannot find parse the doc correctly.
relative path:

```
typora-root-url: ..\..
```

example:
https://ctf-wiki.github.io/ctf-wiki/#/executable/elf/elf_structure

but if I deploy the site localhost, it goes nearly successfully with `typora-root-url: ....`

**Comment by QingWei-Li** [comment]
The root path is relative to your `index.html`.
