### ISSUE TITLE
将导航栏设置为固定后，侧边栏点击定位不正确。

### ISSUE THREAD

**Issue by strongdevx** [QingWei-Li/docsify#259]
设置导航栏为fixed后，
nav {
    position:fixed;   
   }

侧边栏标题点击位置不正确，会顶到导航栏上面。
![image](https://user-images.githubusercontent.com/29698176/30527412-ce9f9968-9c5a-11e7-9fe4-06cd60b0788c.png)

**Comment by youngda** [comment]
请问下怎么解决的？
