### ISSUE TITLE
只能是单页的？不能有其他页吗？

### ISSUE THREAD

**Issue by imcj** [QingWei-Li/docsify#26]
rt

**Comment by QingWei-Li** [comment]
docsify 的文档就是一个多页的 https://github.com/QingWei-Li/docsify/tree/master/docs

**Comment by imcj** [comment]
sorry，没仔细看文档。再提个问题，不能生成静态页面对吧？

cinwell.li <notifications@github.com>于2016年12月14日周三 下午1:38写道：

**Comment by QingWei-Li** [comment]
不能

**Comment by imcj** [comment]
有考虑增加这个功能吗？

cinwell.li <notifications@github.com>于2016年12月14日周三 下午1:42写道：

**Comment by QingWei-Li** [comment]
不考虑，主打特性就是无需编译，动态生成文档页。可以考虑用其他的例如 Gitbook、docpress 等

**Comment by imcj** [comment]
OK。

cinwell.li <notifications@github.com>于2016年12月14日周三 下午1:44写道：
