### ISSUE TITLE
Multiple anchor selectors after page refresh

### ISSUE THREAD

**Issue by snickers2029** [QingWei-Li/docsify#261]
If you have an in-page link, after you click the link the url becomes /#doc?id=xyz
If you refresh the page, and click the link again, it trys to go to /#doc?id=xyz?id=xyz, and you will get this error:
```docsify.min.js:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#testdoc?id' is not a valid selector.
    at s (https://unpkg.com/docsify@4.3.6/lib/docsify.min.js:1:838)
    at B (https://unpkg.com/docsify@4.3.6/lib/docsify.min.js:1:7611)
    at ne.e.$resetEvents (https://unpkg.com/docsify@4.3.6/lib/docsify.min.js:2:17877)
    at https://unpkg.com/docsify@4.3.6/lib/docsify.min.js:1:9865
```

This happens on chrome, but I guess it's not a browser issue. I guess, you just need to check the current url and get rid of the existing selector if present, before appending the new selector?

**Comment by laysent** [comment]
Hi @snickers2029, it should be fixed by #276 and has been published.
