### ISSUE TITLE
支持gitlab吗？

### ISSUE THREAD

**Issue by huayanYu** [QingWei-Li/docsify#266]
在开源中国上部署成功了的，但是gitlab上不会。。。？
是原生不支持么，还是我的操作不对。。。

**Comment by QingWei-Li** [comment]
#246

**Comment by WangShuXian6** [comment]
![image](https://user-images.githubusercontent.com/30850497/63567348-c95a7300-c5a3-11e9-8d94-195758f82349.png)

>在 github 上可以部署，在gitlab 上不能部署

>完全按照文档来部署的，试了很多次都会报错

```
Step 5/11 : RUN /bin/herokuish buildpack build
 ---> Running in 14b17e0bf224
       -----> Unable to select a buildpack
The command '/bin/sh -c /bin/herokuish buildpack build' returned a non-zero code: 1
ERROR: Job failed: exit code 1
```

**Comment by shijunwen** [comment]
> ![图像](https://user-images.githubusercontent.com/30850497/63567348-c95a7300-c5a3-11e9-8d94-195758f82349.png)
> 
> > 在github上可以部署，在gitlab上不能部署
> 
> > 完全按照文档来部署的，试了很多次都会报错
> 
> ```
> Step 5/11 : RUN /bin/herokuish buildpack build
>  ---> Running in 14b17e0bf224
>        -----> Unable to select a buildpack
> The command '/bin/sh -c /bin/herokuish buildpack build' returned a non-zero code: 1
> ERROR: Job failed: exit code 1
> ```
> 
> > 可以像这样提供一个demo吗？
> 
> > https://gitlab.com/pages?page=1

你好，你这个问题解决了吗？我不知道怎么部署到gitlab上。根据文档操作，页面显示不出来
