### ISSUE TITLE
Search Form issue on mobile devices

### ISSUE THREAD

**Issue by gimesi** [QingWei-Li/docsify#271]
When on a mobile device, the "x" to clear the search form doesn't show up. Could it be that it's only triggered on hover?

**Comment by jrappen** [comment]
@gimesi It has neither been showing for me on Firefox/Edge on Win nor on Safari on iOS for a while now. I assume the "x" was removed a while ago. You can use the backspace though to clear the form entry field, also press+hold should work on mobile as well as a temporary workaround to speed things up.
