### ISSUE TITLE
Improve starting to contribute for new people

### ISSUE THREAD

**Issue by alek13** [QingWei-Li/docsify#282]
Hi!
I just try to start contributing and help you in this great project... and...
and I found out that its not so easy to start.
So, I would like (first of all) to help make starting to contribute more easier.

Improvement contributions:
1. Ignore all needed files, so:
    - the last checkbox in PR-template no more will needed
    - all contributors can use `git add . -A`
    - nobody forget any uncommitted files
    - clean `git status`

2. Than it will be great to write more complex [CONTRIBUTING.md](https://github.com/QingWei-Li/docsify/community), because [this description](https://github.com/QingWei-Li/docsify#contributing) is not enough.
> after run:
> `$ npm run bootstrap && npm run dev`
> I get error:
> ```
> Error: Cannot find module './packages/docsify-server-renderer/build.js'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/alek13/projects/docsify/docsify/app.js:4:16)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
> ```

**Comment by QingWei-Li** [comment]
Sorry for my mistake.
You should need run `npm run build:ssr` after running `npm run bootstrap`. I have fixed it via https://github.com/QingWei-Li/docsify/commit/fac7ce693f80d8273f06bdce122cb11ceb950af3

**Comment by alek13** [comment]
Thanks!

However, after this PR, its still some garbage in `git status`:
```
        modified:   dev.html
        modified:   lib/docsify.js
        deleted:    lib/docsify.min.js
        deleted:    lib/plugins/codesponsor.min.js
        deleted:    lib/plugins/emoji.min.js
        deleted:    lib/plugins/external-script.min.js
        deleted:    lib/plugins/front-matter.min.js
        deleted:    lib/plugins/ga.min.js
        modified:   lib/plugins/search.js
        deleted:    lib/plugins/search.min.js
        deleted:    lib/plugins/zoom-image.min.js
        deleted:    lib/themes/buble.css
        deleted:    lib/themes/dark.css
        deleted:    lib/themes/pure.css
        deleted:    lib/themes/vue.css
```
in despite of that we have added `lib/` directory in `.gitignore`.

Git still tracks this files.
Any ideas ?
Maybe it would be better to have separate directories for dev builds and builds for publish in npm ?
In this case we can fully ignore directory for dev and not keep files in git repo, so git will not track them.
However, the `lib/` we will not ignore, but its content will modified only on build before releasing.
So there will no garbage in `git status`.
It will be more comfortable to develop and contribute.

**Comment by QingWei-Li** [comment]
I no idea...
But I still want to keep the `dist` directory, because some users will directly use the code on the git repository.
