### ISSUE TITLE
Folders aren't working.

### ISSUE THREAD

**Issue by jaynagpaul** [QingWei-Li/docsify#288]
[Repo](https://github.com/jaynagpaul/cryptohandbook) 
[Link](https://jaynagpaul.com/cryptohandbook)

From the docs it seems like if I go to $LINK/#/ethereum the README or home.md should be rendered, but this doesn't seem to be the case

**Comment by QingWei-Li** [comment]
You shoud visit `/#/ethereum/`. If the link you visiting is `/#/ethereum`, it will load `ethereum.md`
