### ISSUE TITLE
nav not work on github pages

### ISSUE THREAD

**Issue by rongjihuang** [QingWei-Li/docsify#29]

**Comment by QingWei-Li** [comment]
It's work in the docsify. Can you describe the issue in detail?

**Comment by rongjihuang** [comment]
I use _navbar.md. `$ docsify serve docs` works fine. But through github pages is `_navbar.md 404`.
The navbar do not show properly
You can help me to check why on <https://rjhwang.github.io/rollup-plugin-stylus-compiler>

**Comment by QingWei-Li** [comment]
Maybe you should add `. nojekyll` into `docs/` folder.

**Comment by rongjihuang** [comment]
It works. Thanks!
