### ISSUE TITLE
approve:add the function to generate a pdf file ?

### ISSUE THREAD

**Issue by o624366705** [QingWei-Li/docsify#291]
how to export a pdf or doc file ? this function is very useful, i hope  you can develop it,thanks

**Comment by QingWei-Li** [comment]
Thanks @o624366705 

Can you tell me what you are going to do it?

**Comment by o624366705** [comment]
Provide User's Manual and Operating instructions and Requirement document  as required for Most of the government or enterprise customers,they need a static file. that funny-looking !

**Comment by o624366705** [comment]
I'm a backend developer. I'm not familiar with vue,So I want someone to provide it

**Comment by QingWei-Li** [comment]
Maybe we can generate pdf on the fly by https://github.com/alvarcarto/url-to-pdf-api 

For example:
https://url-to-pdf-api.herokuapp.com/api/render?url=https%3A%2F%2Fdocsify.js.org%2F%23%2Fmarkdown

**Comment by o624366705** [comment]
thanks a lot,it likes to be useful

**Comment by iamchathu** [comment]
@QingWei-Li Does it look good in PDF?
