### ISSUE TITLE
Gitalk plugin issue

### ISSUE THREAD

**Issue by spiritree** [QingWei-Li/docsify#292]
That's where I insert code
```html
<body>
  <div id="app"></div>
</body>
<div id="gitalk-container"></div>
...
```
**only if width < 768px,the container appears**

![2.png](https://om4v1ul08.qnssl.com/docsify2.png)

**when width > 768px and sidebar exists,the container disappears**

![1.png](https://om4v1ul08.qnssl.com/docsify1.png)

How to fix it?thanks

**Comment by jrappen** [comment]
This is not a docsify issue.
