### ISSUE TITLE
[feature request]click sidebar menu add collapse and expand

### ISSUE THREAD

**Issue by strongdevx** [QingWei-Li/docsify#294]
如题，目前的效果是点击展开子级菜单，再次点击不会收起，建议添加此功能，以提高操作的易用性。

**Comment by jrappen** [comment]
@strongdevx It would be great if you could use English so others can follow the discussion.

**Comment by kfchu** [comment]
I also vote for this enhancement.

**Comment by lvyongfeng** [comment]
I also vote for this enhancement.

**Comment by weituotian** [comment]
I also vote for this enhancement.
