### ISSUE TITLE
Move external font css

### ISSUE THREAD

**Issue by egoist** [QingWei-Li/docsify#3]
For the first line in `cdn/path/to/vue.css`:

```css
@import url('https://fonts.googleapis.com/css?family=Roboto+Mono|Source+Sans+Pro:300,400,600');
```

Maybe move the style to 404.html to make it customizable, or any better idea?

**Comment by QingWei-Li** [comment]
I think it should be part of the theme 😅

But I provided a `pure.css` theme in `0.3.0`,  it is easy to customize.

**Comment by egoist** [comment]
At least replace `https://fonts.googleapis.com` with something accessible in China 😂

**Comment by Justineo** [comment]
@egoist AFAIK `https://fonts.googleapis.com` is accessible from mainland China right now.

**Comment by QingWei-Li** [comment]
Okay, I closed it.
