### ISSUE TITLE
Can directly use `/README.md` instead of copy to `/docs/README.md` ?

### ISSUE THREAD

**Issue by rongjihuang** [QingWei-Li/docsify#30]
I think it is very good if use `/README.md` in the root dir. Now `docsify init docs` would copy it to `/docs`. It make me to maintain two README.md file. That is bad idea.

**Comment by egoist** [comment]
since you can't load `repo/README.md` if you serve `repo/docs` for github pages

quick solution, add a `home` option which points to the disired README.md, eg: `https://raw.githubusercontent.com/QingWei-Li/docsify/master/README.md`

**Comment by QingWei-Li** [comment]
@egoist Good idea

**Comment by rongjihuang** [comment]
Wonderful
