### ISSUE TITLE
支持根目录_sidebar.md做索引

### ISSUE THREAD

**Issue by janryWang** [QingWei-Li/docsify#301]
目前如果要组织文档，往往是需要对文档进行目录化拆分维护，在根目录上提供一个索引_sidebar.md，目前docsify有个问题，强制要求子目录也要存在_sidebar.md，不然会出现404报错，比如：

目录结构

```
root
   --dir1
      --- topic1.md
      --- topic2.md
  --dir2
      --- topic1.md
      --- topic2.md
  --_sidebar.md
  --readme.md
```
_sidebar.md

```
- [dir1](dir1/topic1.md)
   - [topic1](dir1/topic1.md)
   - [topic2](dir1/topic2.md)
- [dir2](dir2/topic1.md)
   - [topic1](dir2/topic1.md)
   - [topic2](dir2/topic2.md)
```

建议提供一个参数
loadRootSidebar，保证只加载根目录的_sidebar.md文件

**Comment by QingWei-Li** [comment]
你可以配置 alias https://docsify.js.org/#/zh-cn/configuration?id=alias

**Comment by janryWang** [comment]
@QingWei-Li 如果目录结构很深的话，alias配置起来就太麻烦了啊

**Comment by QingWei-Li** [comment]
```js
alias: {
      '/.*/_sidebar.md': '/_sidebar.md'
    }
```

**Comment by janryWang** [comment]
@QingWei-Li ok，感谢

**Comment by aierui** [comment]
请问需要在根目录和子目录配置 _sidebar.md，但是子目录下面其他目录不配置，如何使用 alias 呢？🤔

**Comment by shenxiang216** [comment]
> 不生效，我的还是会报404

**Comment by lume-vercel** [comment]
Tip for english speakers: if you've enabled `routerMode: 'history'`, you may want to configure the sidebar file to be accessed from the root no matter the path using `alias`. See the example:

https://docsify.js.org/#/configuration?id=alias

**Comment by trusktr** [comment]
Tip for english speakers: if you've enabled `routerMode: 'history'`, you may want to configure the sidebar file to be accessed from the root no matter the path using `alias`. See the example:

https://docsify.js.org/#/configuration?id=alias

```js
window.$docsify = {
  routerMode: 'history',
  alias: {
    '/.*/_sidebar.md': '/_sidebar.md',
  },
};
```
