### ISSUE TITLE
[Enhancement ] 在设置了 homepage 的情况下 侧边栏是否也应当高亮？

### ISSUE THREAD

**Issue by PanJiaChen** [QingWei-Li/docsify#304]
`homepage: 'started.md'`  如果我这样设置了 `homepage` ,  页面是显示了 `started.md` 的内容，但侧边栏却不高亮，还是蛮奇怪的。

个人建议：
要么如 [vue-router](https://router.vuejs.org/zh-cn/) 那样 ，默认高亮 `homepage` 的路由
或者干脆设置了 `homepage` 直接将路由重定向到设置的路由 
如 `http://localhost:3000/#/` => `http://localhost:3000/#/started`

**Comment by jrappen** [comment]
@PanJiaChen It would be great if you could use English so others can follow along the discussion.

**Comment by PanJiaChen** [comment]
Translation:
if l set the homepage like `homepage: 'started.md'` , but the `sidemenu` is not actived and hightlight , it is not perfect.

my suggestion：
 - like `[vue-router](https://router.vuejs.org/en/)` highlight the `homepage` which you set
 - also you can redirect the router if you are set the  `homepage`. such as `http://localhost:3000/#/` => `http://localhost:3000/#/started`

**Comment by lvyongfeng** [comment]
我也有相同的建议！@PanjiaChen
