### ISSUE TITLE
提示静态资源找不到

### ISSUE THREAD

**Issue by janryWang** [QingWei-Li/docsify#307]
![snip20171110_27](https://user-images.githubusercontent.com/4060976/32640744-be2c4320-c58f-11e7-8b1c-1c826f043b41.png)

**Comment by QingWei-Li** [comment]
emm 可能是网络或者 cdn 的节点问题，你重试几次。
如果还有问题可以换 cdn 比如 https://cdn.jsdelivr.net/npm/docsify/

**Comment by janryWang** [comment]
@QingWei-Li 能否在docsify init的时候用cdn，而不是用unpkg呢

**Comment by QingWei-Li** [comment]
好的，你可以到 [docsify-cli](https://github.com/QingWei-Li/docsify-cli/issues) 提 issue，我后面加入这功能。
