### ISSUE TITLE
支持任意URL

### ISSUE THREAD

**Issue by Gcaufy** [QingWei-Li/docsify#31]
能否支持任意URL，这样我就可以放在我自己的服务器上

比如：
```
docsify('https://raw.githubusercontent.com/myrepo/master/README.md')
```

**Comment by QingWei-Li** [comment]
没看懂「任意 URL」指的是什么意思。如果只是想部署在自己服务器上，并不需要做任何额外的操作，如果是 nginx 只需要用下面的配置即可

```nginx
server {
  listen 80;
  server_name  your.domain.com;

  location / {
    alias /path/to/dir/of/docs;
    index index.html;
  }
}
```


参考:

- https://github.com/QingWei-Li/docsify/issues/18
- https://docute.js.org/#/?id=deploy-to-vps

**Comment by Gcaufy** [comment]
部署在其它服务器， 但是使用的是 github.com/myrepo/README.md
如何指定md文件，而不是默认取./docs/README.md

**Comment by QingWei-Li** [comment]
现在 html 入口文件要和 md 文档文件在同个目录下才有效。不过看起来可以加一个 `basePath` 的选项。

**Comment by Gcaufy** [comment]
刚看了一下代码，xhr的。那么就无法避免跨域问题。
求提供生成静态HTML的命令行，不要动态拉取README.md
如：
```
docsify ./docs/README.md  => html.html
docsify http://www.xxx.com/README.md  => html.html
```

**Comment by QingWei-Li** [comment]
特色是动态生成而非编译静态文件 😂 不打算支持这个功能

**Comment by bigggge** [comment]
问下nginx配置，为什么第一种配置docs显示404，放在根目录就可以

       location /docs/ {
          root /home/docs;
          index index.html index.htm;
        }

        location / {
          root /home/docs;
          index index.html index.htm;
        }

**Comment by lxiaoxiang** [comment]
我也遇到这个问题，把文件名小写试试

**Comment by istommao** [comment]
用caddy 要怎么配置，我配起来都是空白页？

**Comment by EvanLind** [comment]
> 没看懂「任意 URL」指的是什么意思。如果只是想部署在自己服务器上，并不需要做任何额外的操作，如果是 nginx 只需要用下面的配置即可
> 
> ```nginx
> server {
>   listen 80;
>   server_name  your.domain.com;
> 
>   location / {
>     alias /path/to/dir/of/docs;
>     index index.html;
>   }
> }
> ```
> 
> 参考:
> 
> * #18
> * https://docute.js.org/#/?id=deploy-to-vps

The right vps nginx conf is:
```json
server {
  listen 80;
  server_name  your.domain.com;

  location / {
    root /path/to/dir/of/docs;
    index index.html;
  }
}
```

**Comment by m5xhsy** [comment]
怎么去掉url上面那个#/啊

**Comment by QingWei-Li** [comment]
> 怎么去掉url上面那个#/啊

https://docsify.js.org/#/configuration?id=routermode

**Comment by Subilan** [comment]
> > 没看懂「任意 URL」指的是什么意思。如果只是想部署在自己服务器上，并不需要做任何额外的操作，如果是 nginx 只需要用下面的配置即可
> > ```nginx
> > server {
> >   listen 80;
> >   server_name  your.domain.com;
> > 
> >   location / {
> >     alias /path/to/dir/of/docs;
> >     index index.html;
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参考:
> > 
> > * [Deploying on vps #18](https://github.com/docsifyjs/docsify/issues/18)
> > * https://docute.js.org/#/?id=deploy-to-vps
> 
> The correct vps nginx conf is:
> 
> ```nginx
> server {
>   listen 80;
>   server_name  your.domain.com;
> 
>   location / {
>     root /path/to/dir/of/docs;
>     index index.html;
>   }
> }
> ```
> 
> Or you have to change your static file owner to nging conf user https://stackoverflow.com/questions/16808813/nginx-serve-static-file-and-got-403-forbidden

It's been a few years since I lastly used Docsify, and today I tried to deploy some old pages with nginx, using the configuration from the document (same as what the author mentioned in this issue), and encountered the 403 problem quite smoothly. Changing `alias` to `root` is the solution.

Thank you, my friend, you saved my day :D
