### ISSUE TITLE
Can I use my own theme?

### ISSUE THREAD

**Issue by cardeo** [QingWei-Li/docsify#321]
Hi, just wondering if there is a way to use my own CSS theme with docsify?

I tried creating a css file in the /docs directory then linking to it in the index.html file but it looks like it gets ignored.

**Comment by QingWei-Li** [comment]
Hi,
Yes, you can customize the theme.

These are some examples I found in [showcase](https://github.com/QingWei-Li/docsify#showcase)

- https://ned.im/noty/
- https://marionebl.github.io/commitlint/
- https://mythbusters.js.org/

I'm not sure if the default theme file overrides your css style, maybe you could just use [prue.css](https://unpkg.com/docsify/themes/pure.css) as the base style and develop your theme...
