### ISSUE TITLE
怎样导入第三方库，并在项目中使用

### ISSUE THREAD

**Issue by fewiki** [QingWei-Li/docsify#323]
code
```
import Element from 'element-ui'
Vue.use(Element)
```

如上面代码,我想把第三库入进来使用,没有找到入口在如里写,非常感谢

**Comment by QingWei-Li** [comment]
请使用 CDN 的方式引入

**Comment by fewiki** [comment]
谢谢了。 第三方的库可以引。  其实我是想引入我自己写的一些组件，做成一个说明文档。
我想全局引入，Vue.use(’name‘)  这个不知道在哪里去写，非常感谢

![image](https://user-images.githubusercontent.com/13325335/33920430-e01edf46-dff8-11e7-8d32-bdf564469b8f.png)

**Comment by QingWei-Li** [comment]
目前只有少数主流浏览器支持 ES Module，不建议使用。你的库需要提供 umd 模块，要能通过 CDN 的方式引入。

**Comment by fewiki** [comment]
好的，非常感谢，我再研究转换一下

**Comment by freshGi** [comment]
请问您最后如何处理的呢？
