### ISSUE TITLE
Inconsistent ID Anchor Jumps

### ISSUE THREAD

**Issue by DerekGallardo01** [QingWei-Li/docsify#332]
Same page anchor jumps have no problem.
Different page anchor jumps with no ID - no problem.

BUT

When I need to jump to another page that has an ID referenced....

The anchor jump doesn't directly go the ID but near the ID.

HOWEVER

I noticed if I go for a second try...the anchor jump does in fact go to the ID.

What can be the issue?

**Comment by QingWei-Li** [comment]
Can you provide a link?
