### ISSUE TITLE
想让超链接指向一个文档的地址，点击超链接可以下载该文档

### ISSUE THREAD

**Issue by ACEsLegendary** [QingWei-Li/docsify#334]
比如，我现在想要实现，一个超链接，可以下载一些word文档。
但是似乎是不行，除非url本身就是以".md"或者以".html"结尾的，所有的请求都被追加上了".md"，然后404错误。
可不可以提供一个配置来豁免一些url，使得可以直接访问这些url而不是一定使用parser的逻辑来处理。

**Comment by ACEsLegendary** [comment]
找到解决办法了，noCompileLinks配置一个路由即可。问题是现在需要写对应链接的完整url才行。

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/helpers?id=ignore-to-compile-link

**Comment by ACEsLegendary** [comment]
thanks for information
