### ISSUE TITLE
原有的文档服务，使用id索引带有ACL索取数据，前端想改造使用docsify，请教~

### ISSUE THREAD

**Issue by wsd1** [QingWei-Li/docsify#336]
如标题，因为不是基于文件系统的文档索取，所以，在改造docsify的过程中遇到问题。

请教：get过程头部需要 authorization，是否只能直接在 src/core/fetch 改代码。

是否还有其他什么更好的 over ride手段？

**Comment by QingWei-Li** [comment]
直接改 `src/core/fetch` 里好一些

**Comment by wsd1** [comment]
明白，开个branch总是有点别扭，有机会使用 plugin解决问题吗？  你看，这个小小的需求其实很容易能够纳入到大框架里来的~~

**Comment by QingWei-Li** [comment]
需要的话我可以开放配置项，但是如果 auth 信息写在配置项，例如 `index.html` 文件里不会再招摇么。

**Comment by wsd1** [comment]
我的想法是 配合自写的 vue component来运作，后者用来提供一个输入passwd的widegt。大致看了plugin的接口，应该能访问到全局结构，如此，应该可以解决问题。

**Comment by wsd1** [comment]
需要的可能就是 在 fetch这里 能灵活点

**Comment by wsd1** [comment]
👌  好
