### ISSUE TITLE
部署到github之后访问报404

### ISSUE THREAD

**Issue by li10217** [QingWei-Li/docsify#339]
[这是我的[项目地址](https://github.com/li10217/LearningNotes)，我按照文档上的方式部署到github之后，访问[git pages](https://li10217.github.io/LearningNotes/)的网址报404，
![git1](https://user-images.githubusercontent.com/23067397/34594950-0e2244fa-f20f-11e7-849d-10eb2219d0e5.png)
![git2](https://user-images.githubusercontent.com/23067397/34594951-0e542574-f20f-11e7-9b5a-094ff552b139.png)
![git3](https://user-images.githubusercontent.com/23067397/34594952-0e830768-f20f-11e7-85b8-26f0aef82fe7.png)

**Comment by li10217** [comment]
能帮我看下怎么回事吗？

**Comment by li10217** [comment]
不好意思啊现在显示了，可能有延迟吧

**Comment by is-liyiwei** [comment]
请问下，你这个问题解决了吗？我也是按照官方文档来，结果报错404了，但是我能够进入页面，404是这个找不到，在控制台里面的 GET https://is-liyiwei.github.io/im-vuer/README.md 404 ()  docsify.min.js:1
