### ISSUE TITLE
如何设置页面锚点？

### ISSUE THREAD

**Issue by 839891627** [QingWei-Li/docsify#343]
我需要在如图页面添加锚点，指向另一个接口说明，直接写 `[去这里](#abc)`不可以
![image](https://user-images.githubusercontent.com/10300651/34709409-15639bce-f552-11e7-84a1-25434b82fa11.png)

**Comment by QingWei-Li** [comment]
```text
[去这里](#abc)
```

这么写是对的，如果无法正确运行请提供 demo
