### ISSUE TITLE
有侧边栏折叠功能吗？

### ISSUE THREAD

**Issue by 839891627** [QingWei-Li/docsify#344]
不拆分成过个文件，怎么如果可以设置可否　折叠　就好了
![image](https://user-images.githubusercontent.com/10300651/34710074-de30ed8e-f554-11e7-9fb2-588e6951dbc5.png)

**Comment by QingWei-Li** [comment]
Duplicate of #294

**Comment by weituotian** [comment]
I also vote for this enhancement.

**Comment by popdo** [comment]
虽然2020年了，同样建议能改进这个功能，文档很复杂 很多三级的侧边栏，现在是点击二级菜单之后他下面的三级菜单也全部是展开的，非常不便于浏览，能否让所有的侧边栏子菜单只有单独点击了才展开。
