### ISSUE TITLE
Sidebar help - collapsing 

### ISSUE THREAD

**Issue by ItsPugle** [QingWei-Li/docsify#350]
I've noticed that on [the Docsify docs](https://docsify.js.org), when you click on 'Configuration', under 'Customization' it expands to have more subheadings that weren't there beforehand - how is this done?

I've had a look at the source code, and I still don't understand how this is done :laughing:

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/configuration?id=sub-max-level
