### ISSUE TITLE
Using the vertical line symbol inside a code block within a table breaks the table

### ISSUE THREAD

**Issue by davidelvar** [QingWei-Li/docsify#366]
So the issue that I'm having is that I'm creating documentation for a software which uses smarty variables such as **{$line.subtotal|money}**. Issue that I'm having is with the vertical line symbol being used inside a code block, within a table. It breaks the table becouse the same symbol is being used to format the table itself. I wanted to display all the variables in a table such as:

| Variable                           | Output                                       |
| ----------------------------------- |:------------------------------------------------------------------------------:|
| `{$line.price|money}`                                                 | Item description   |

But as you can see above it breaks the table. Is there any way to ignore all symbols within a code block or any other solution?

Any help appreciated.

**Comment by QingWei-Li** [comment]
use `{$line.subtotal\|money}`

for example

| Variable                           | Output                                       |
| ----------------------------------- |:------------------------------------------------------------------------------:|
| `{$line.price\|money}`                                                 | Item description   |

**Comment by davidelvar** [comment]
For some reason it does not work for me. Have you tried it in the script itself?

Got the following code:

```
| Variable                                                                  | Output                                                                         |
| ------------------------------------------------------------------------- |:------------------------------------------------------------------------------:|
| `{img_tag name=$product.images[image].name\|product_image_url:'large'}`   | Displays the product image in large format. Can be modified to use others.     |
| `{$product.was_price\|money}`                                             | Displays the product was price if there is any.                                |
| `{$product.price\|money}`                                                 | Displays the current product price in the default currency.                    |
```

It works on github as you can see below:
| Variable                                                                  | Output                                                                         |
| ------------------------------------------------------------------------- |:------------------------------------------------------------------------------:|
| `{img_tag name=$product.images[image].name\|product_image_url:'large'}`   | Displays the product image in large format. Can be modified to use others.     |
| `{$product.was_price\|money}`                                             | Displays the product was price if there is any.                                |
| `{$product.price\|money}`                                                 | Displays the current product price in the default currency.                    |

But for some reason it does not work in docsify?

[See how it shows up in my installation here](http://jmp.sh/wyjDVbI) <- This uses the same code example as above.

**Comment by QingWei-Li** [comment]
This is marked bug https://github.com/chjj/marked/issues/595

Meanwhile, a workaround exists: use `&#124;` instead of `|`.

```markdown
Foo | Bar
--- | ---
<code>yes &#124; no</code> | bar
```

Foo | Bar
--- | ---
<code>yes &#124; no</code> | bar

**Comment by davidelvar** [comment]
Appreciate it, that works for now.
