### ISSUE TITLE
Do we have a URL based search mechanism?

### ISSUE THREAD

**Issue by cyanzhong** [QingWei-Li/docsify#368]
With that design, we could easily launch an action like: `https://docsify.now.sh/search?q=test`, and the keywords `test` will be filled to the search field, just like you type it manually.

That would be helpful to implement a `search in` feature.

How does it sound?

**Comment by QingWei-Li** [comment]
Actually, this feature has been implemented via https://github.com/QingWei-Li/docsify/issues/156

You should use `s` like https://docsify.now.sh/?s=quick

**Comment by cyanzhong** [comment]
Awesome! Thank you!
