### ISSUE TITLE
_sidebar的加载问题。

### ISSUE THREAD

**Issue by prlei** [QingWei-Li/docsify#372]
文档中写到：
`
_sidebar.md 的加载逻辑是从每层目录下获取文件，如果当前目录不存在该文件则回退到上一级目录。例如当前路径为 /zh-cn/more-pages 则从 /zh-cn/_sidebar.md 获取文件，如果不存在则从 /_sidebar.md 获取。
`
可是我用根目录的一个_sidebar.md就足够了，可是在“F12”的时候会有错误，强迫症表示是否考虑加一个开关，让我只从根目录加载，使得"F12"没有错误。
`
unpkg.com/docsify@4.5.7/lib/docsify.min.js:1 GET http://localhost:3000/zh-cn/process/_sidebar.md 404 (Not Found)
`
又或是我读文档不仔细，没有找到解决方法？

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/configuration?id=alias

**Comment by prlei** [comment]
果然是我阅读不仔细，不过是否需要在文档中加入此功能更详细一些的描述。
