### ISSUE TITLE
Copy to clipboard plugin not working

### ISSUE THREAD

**Issue by hemanrnjn** [QingWei-Li/docsify#374]
I am trying to use the copy code to clipboard plugin in my docsify generated documentation.
Following is my config.js file in which I have written my configuration for docsify :

config.js - 

`window.$docsify = {
      name: '',
      repo: '',
      subMaxLevel: 2,
      loadSidebar: true,
      loadSidebar: './_sidebar.md',
      coverpage: true,
      coverpage: './cover.md',
      homepage: true,
      homepage: './home.md',
      auto2top: true,
      search: 'auto',
      executeScript: true
      plugins: [
        window.DocsifyCopyCodePlugin.init()
      ]
}`

I have included this config.js file in my index.html file along with other necessary css and js file correctly.

The plugin fails to run and throws an error in the console from my config.js file - 

`config.js:14 Uncaught SyntaxError: Unexpected identifier`

**Comment by QingWei-Li** [comment]
`true plugins: ...` missing`,`

**Comment by hemanrnjn** [comment]
@QingWei-Li oh, my bad.. that was really silly. Thanks though.
