### ISSUE TITLE
Hosting on Firebase

### ISSUE THREAD

**Issue by ItsPugle** [QingWei-Li/docsify#377]
I've been mucking around with Docsify and [Firebase Hosting](https://firebase.google.com/products/hosting/), and I'm pretty confident with it. Any objections to me making a PR for /deploy with instructions?

**Comment by QingWei-Li** [comment]
PR is welcome. 😇

**Comment by ItsPugle** [comment]
Coming Soon:tm: to a Pull Request near you!

I should have one done before the end of next-week, at the latest
