### ISSUE TITLE
Docsify always requests _sidebar.md and _navbar.md on nested folders

### ISSUE THREAD

**Issue by silentHoo** [QingWei-Li/docsify#380]
First: Thanks for the helpful and very simple to use documentation library.

When I put my markdown files into subdirectories, Docsify always requests `_sidebar.md` and `_navbar.md` for each link which correctly returns a 404 from the server, because I don't have such files in each subfolder.

For example, I have the following structure:

```
src/docs/README.md
src/_navbar.md
src/_sidebar.md
src/docs/reference/index.md
src/docs/reference/my-ref1.md
src/docs/reference/my-ref2.md
src/docs/api/interface1.md
src/docs/api/interface2.md
```

All the links in the `_sidebar.md` point to something like `docs/reference/my-ref1.md` and `docs/api/interface1.md`.

Do I miss some configuration so that docsify doesn't request the side- and navbar on each link visit?

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/more-pages?id=sidebar

You can use alias option.

**Comment by silentHoo** [comment]
Oh, I overread it. Awesome, thank you 👍

**Comment by shenxiang216** [comment]
好像没有用呀？
