### ISSUE TITLE
带封面图的时候在手机 Chrome 显示不正常

### ISSUE THREAD

**Issue by Binaryify** [QingWei-Li/docsify#381]
封面顶部会出现未被蒙层遮罩的地方

**Comment by Binaryify** [comment]
在 PC Chrome 上看是正常的,但是手机上是不正常的

**Comment by QingWei-Li** [comment]
手机设备和浏览器版本能报一下么，我在 android x5 和 chrome 上均正常。
以及你的 cover 的配置也发一下

**Comment by Binaryify** [comment]
感谢修复

**Comment by Alexander-Huang** [comment]
Hasn't been fixed yet
![Screenshot_20210213-171313_Chrome](https://user-images.githubusercontent.com/42209822/107846448-d49c0100-6e1e-11eb-8f98-479a2c100194.png)

This issue is reported by several users.
I tried adjusting the size of the picture but with no luck.
