### ISSUE TITLE
显示封面时如何隐藏掉README的内容?

### ISSUE THREAD

**Issue by windwalker** [QingWei-Li/docsify#382]
在添加了封面后, 首页内容会由_coverpage.md 与 README.md两个文档内容按照上下结构呈现。

我想问一下如何隐藏掉 README.md 里面的内容?  现在有支持这个的配置么?

**Comment by QingWei-Li** [comment]
不支持

**Comment by windwalker** [comment]
可以考虑增加下这个配置么? 

大部分的文档网站都是将封面页和文档分开显示的，我也希望我的文档能这样显示。
