### ISSUE TITLE
Plug-ins: "beforeEach" hook not working anymore

### ISSUE THREAD

**Issue by igor-go** [QingWei-Li/docsify#394]
Hi,
I really love what you are doing in this project. However, since about one week ago, I'm facing a kind of bug with some plugins I wrote by using the "beforeEach" hook. It seems that it is not executed anymore. I made a fresh install with the last updates and I can see that while "afterEach" hooks are working perfeclty, they don't run if i change "after" by "before".... 

any ideas?

many thanks, 

Igor

**Comment by QingWei-Li** [comment]
I fixed a few minutes ago. Please upgrade to `v4.6.2`.

**Comment by iolaizola** [comment]
Great Thank you!!!!!
