### ISSUE TITLE
Add option to change location of sidebar toggle

### ISSUE THREAD

**Issue by ruisilva450** [QingWei-Li/docsify#396]
At this point we have the toogle on the bottom left.
It would be usefull on mobile to be able to change his location to the top left or even right (this maybe require changing the sidebar location to the right so maybe later)

**Comment by QingWei-Li** [comment]
You can modify CSS as your like. This is not an important feature.

**Comment by edgexie** [comment]
why not set sidebar toggle on top default?

**Comment by soneji** [comment]
If anybody else is coming across this issue and can't find any solutions online I fixed it by adding this to a `<style>` block underneath all the existing `<link...` stylesheets

```html
<style>
    .sidebar-toggle {
      position: relative !important;
      top: 0 !important;
    }
</style>
```

**Comment by Fmstrat** [comment]
Easiest way as of 2024:

```
.sidebar-toggle {
	background-color: unset;
	position: fixed !important;
	top: 0 !important;
	bottom: auto !important;
	padding: 10px 10px 10px 10px !important;
}

@media screen and (max-width: 768px) {
	.markdown-section {
		padding: 16px 16px 16px 36px !important;
	}
}
```
