### ISSUE TITLE
Remove blank in the sidebar for headings linking to other pages

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#4]
When I use

    ## Getting Started

    ### [Snip](/Getting-Started#snip)

an unwanted blank line appears in the side bar:
![snipaste20161127_160403](https://cloud.githubusercontent.com/assets/2010459/20646710/b3f033b6-b4bb-11e6-89c8-f952492913cb.png)

It corresponds to `<a class="section-link" href="#snip"></a>`, which I think should be removed.

---

Also, I am wondering if there is any way that I can hide certain headings in the content but keep them visible in the sidebar. The reason is that I have multiple pages and I would like to keep a consistent sidebar for all pages, while the content of each page stays clean and will not show the headings linking to other pages.

**Comment by QingWei-Li** [comment]
It's just a toc, I do not think it can be used as navigation. Maybe you can override style. 
If only less navigation, you can refer to https://qingwei-li.github.io/docsify/zh-cn#导航. You have any ideas?

**Comment by QingWei-Li** [comment]
Maybe we can support custom sidebar, what do you think? such as

```html
<aside>
  <ul>
    <li>
      <a href="/Getting Started">Getting Started</a>
      <ul>
        <li><a href="/Getting-Started#snip">Snip</a></li>
      </ul>
    </li>
  </ul>
</aside>
```

Or global variables

```html
<script>
window.Docsify.sidebar = [
  { path: '/xxx', name: 'xxx', children: [] }
]
</script>
```

**Comment by QingWei-Li** [comment]
For now, we can custom sidebar, such as
![image](https://cloud.githubusercontent.com/assets/7565692/20647425/de5ab1c2-b4ce-11e6-863a-135868f2f9b4.png)

```html
<script>
  window.sidebar = [
    { slug: '/', title: 'Home' },
    {
      slug: '/pageA',
      title: 'page A',
      children: [
        { slug: '/pageA/childrenB', title: 'children B' }
      ]
    },
    { slug: '/PageC', title: 'Page C' }
  ]
</script>
<script src="/lib/docsify.js" data-sidebar="sidebar"></script>
```

If you approve the feature, I'll publish it in next minor version. 😄

**Comment by liulex** [comment]
I think the current top navbar is very good for language switching. Adding other menu items seems not suitable. However, it would be very nice it if the drop-down list feature can be added on it.

Oh, while I'm writing this, I see your updates...
Awesome! Your solution can offer me the desired navigation and also keep my .md files clean (no adding titles of other pages)! :thumbsup:

**Comment by QingWei-Li** [comment]
The dropdown list can be achieved purely through CSS, maybe  the users to achieve better.

**Comment by liulex** [comment]
OK. I will try that. Thanks!
