### ISSUE TITLE
Arbitrary background color for cover page

### ISSUE THREAD

**Issue by Leopoldthecoder** [QingWei-Li/docsify#40]
Currently the background of cover page is generated [randomly](https://github.com/QingWei-Li/docsify/blob/50addfdac699ef2cc5a01b6df3184d60aefa7cf9/src/tpl.js#L40). In some cases, when put together,  the generated color and the coloring of project's logo don't quite match. Any thoughts on letting users configure their own background colors?

Another thing, `Math.floor(Math.random() * 255)` makes it impossible for hue to be greater than 255, thus the background color may never be purple or pink. Is this on purpose?

**Comment by QingWei-Li** [comment]
I will add a new feature to support custom background color or image. likes

```markdown

![logo](_media/icon.svg)

# docsify <small>1.3.3</small>

> A magical documentation site generator.

- Simple and lightweight (~12kb gzipped)
- Multiple themes
- Not build static html files


[GitHub](https://github.com/QingWei-Li/docsify/)
[Get Started](#quick-start)

![](background.png)
<!-- or  -->
![](red)
<!-- or  -->
![](linear-gradient(to left bottom, #b3ffc8 0%, #eeffb3 100%))
```

**Comment by Leopoldthecoder** [comment]
Awesome!

**Comment by QingWei-Li** [comment]
![image](https://cloud.githubusercontent.com/assets/7565692/21576010/c818d3b4-cf5c-11e6-893b-c079b07b9a0e.png)

1.4.0 is now released!

**Comment by Leopoldthecoder** [comment]
哦

**Comment by QingWei-Li** [comment]
你大爷

**Comment by Leopoldthecoder** [comment]
别闹，今天就试试

**Comment by mazeitor** [comment]
hi, I am trying this configuration to have an image as background and also the gradient on it, but the results are not like the screenshot you posted. the version i am using is 4.6.10.

anyone can help ? thanks

**Comment by ed1chandler** [comment]
I'm in the same boat.  My background image is stuck at a fixed size no matter what I do.  How do you duplicate the full-screen responsive background image as shown in the image above? Thanks.
