### ISSUE TITLE
请教怎么插入一个异步的js脚本以做代码演示

### ISSUE THREAD

**Issue by xiaodianxie** [QingWei-Li/docsify#400]
在gitbook中可以如下形式使用：<script async src="//jsfiddle.net/xiaodianxie/9nLnLfy0/4/embed/"></script>
相当于在文档插入iframe展示了代码示例，而在docsify中插入script会被自动忽略，请问这种场景该如何处理？

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/plugins?id=external-script
