### ISSUE TITLE
Error running in Azure Web App

### ISSUE THREAD

**Issue by seankearon** [QingWei-Li/docsify#405]
I'm trying to run Docsify in an Azure Web App.  I'm getting a 404 that looks like there's something I'm missing about configuring the site, perhaps?

    Failed to load resource: the server responded with a status of 404 (Not Found)
    index.html/README.md 

Has anyone had success using Docsify in an Azure Web App?

(I've also asked this on StackOverflow [here](https://stackoverflow.com/questions/49073138/error-using-docsify-in-an-azure-web-app), plus added a `docsify` tag!)

**Comment by QingWei-Li** [comment]
Do you visit like `example.com/index.html`?
Please remove /index.html

**Comment by seankearon** [comment]
No, I was visiting the root site (`example.com`), not `index.html `.

**Comment by QingWei-Li** [comment]
Please show your configuration

**Comment by seankearon** [comment]
Sure, this is what I'm using:

    window.$docsify = {
      name: 'My Site Documentation',

      loadSidebar: true,
      alias: {
        '/.*/_sidebar.md': '/_sidebar.md'
      },
      search: {
        noData: {
          '/': 'No results!'
        },
        search: [
          '/',            // => /README.md
          '/section1/article1',       // => /guide.md
        ],

        placeholder: {
          '/': 'Search'
        }
      },
      subMaxLevel: 1,
      paths: 'auto',
    }

**Comment by seankearon** [comment]
Plus these:

    <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
    <script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>

**Comment by seankearon** [comment]
Okay, think I've made some progress on this.  I've been looking at this article from James Randall:

https://www.azurefromthetrenches.com/serving-static-markdown-content-from-asp-net-mvc-to-javascript/

I've added the configuration settings he mentions at the start to the `web.config` file.  After that, Docsify serves the pages from the markdown files.  :)  

```
<configuration>
  <system.webServer>
    <staticContent>
      <remove fileExtension=".md" />
      <mimeMap fileExtension=".md" mimeType="text/markdown" />
    </staticContent>
  </system.webServer>
</configuration>
```

However, I am still getting errors in the console, so I'm trying to add the CORS handler he mentions in the second half.  Will come back soon...

**Comment by seankearon** [comment]
It seems that the errors in the console are my bad - I've got some broken links in the articles I'd uploaded.

Also, I don't think the CORS handling from James Randall's article is needed.  

I'll try some more tomorrow and update this thread on progress.

**Comment by seankearon** [comment]
Yes, this is working nicely.  Thanks for your help, @QingWei-Li - closing.
