### ISSUE TITLE
想了解一下docsify怎么生成静态页面？

### ISSUE THREAD

**Issue by henryzp** [QingWei-Li/docsify#41]
通过`docsify serve`来启动服务。

那怎么让服务在后台运行？

我一开始想到的是用PM2，但试了一下无法集成。

像`gitbook`，它有一个`gitbook build`的命令，来生成`_books`目录，然后nginx指向它里面的index.html，就能跑起来访问了。

所以我想问`docsify`有没有这样的方法？还是要怎么做？看了一下命令，目前只支持：

- init
- serve

**Comment by QingWei-Li** [comment]
docsify-cli 只是拿来做本地预览的，并不是让你部署在服务器上。docsify 只是一段 js 脚本，放在 index.html 文件里后会动态请求 markdown 文件并渲染成 DOM，都是静态文件。

**Comment by QingWei-Li** [comment]
还有它并没有生成静态页面，都是动态渲染的。

**Comment by henryzp** [comment]
@QingWei-Li 

那我如果想部署在服务器上，要怎么搞？

**Comment by QingWei-Li** [comment]
https://docute.js.org/#/zh-Hans/?id=%E9%83%A8%E7%BD%B2%E5%88%B0-vps

(docute 也是同样的工具，部署到服务器的做法和这个相同)

**Comment by LancerComet** [comment]
看来大家都想部署在本地啊，不过作者的意图应该只是一个简单的静态文档工具，蛤蛤

**Comment by henryzp** [comment]
@QingWei-Li 谢谢。。我试试

**Comment by QingWei-Li** [comment]
@LancerComet 如果这样的话，我们可以完善 docsify-cli，当初做这个命令行工具就只是为了方便预览。其实还可以加入 live reload、快速启动 serve （不需要写 index.html 文件，只要当前目录有 markdown 文件即可）

**Comment by LancerComet** [comment]
@QingWei-Li 之后就去瞅瞅

**Comment by henryzp** [comment]
发现其实布署挺方便的，只要指向docs下面的index.html就行了

谢谢！
