### ISSUE TITLE
Images problem

### ISSUE THREAD

**Issue by mohsens22** [QingWei-Li/docsify#412]
Hello!
My repository documentation has some images in their own folder but docsify refuses loading it.
[Here](https://github.com/mohsens22/MSharp.Docs) is my repository and [here](https://mohsens22.github.io/MSharp.Docs/#/) is the website.
As an example: 
![image](https://user-images.githubusercontent.com/22152065/36951503-e138e9c4-2019-11e8-9261-55a97683ea49.png)
Everything is working [Here](https://github.com/mohsens22/MSharp.Docs/tree/master/Tutorials/1) in the github
![image](https://user-images.githubusercontent.com/22152065/36951528-1947f94a-201a-11e8-8b93-70ef44a3c895.png)
But it's not working [here](https://mohsens22.github.io/MSharp.Docs/#/Tutorials/1/README)

Can you help me fix this?

**Comment by QingWei-Li** [comment]
You should use `Tutorials/1/ContactList.PNG`.
This is a known problem, I haven't idea how to solve it.

**Comment by mohsens22** [comment]
![image](https://user-images.githubusercontent.com/22152065/36986704-baae618a-20af-11e8-903b-6da0a45aec8c.png)
with
`![Contact List](Tutorials/1/ContactList.PNG "Contact List")`
Github refuses loading it
