### ISSUE TITLE
Image in the sidebar!

### ISSUE THREAD

**Issue by mohsens22** [QingWei-Li/docsify#416]
Hello.
I see a really wired thing. My document shows a picture in sidebar which shouldn't.
![image](https://user-images.githubusercontent.com/22152065/37084747-90f838fc-2208-11e8-8a0d-b7fcf5ee945a.png)
this is the markdown :
https://github.com/Geeksltd/MSharp.Docs/blob/599008884adcff81acce99bf9d6bffeb185898e0/Basics/Concepts.md

**Comment by QingWei-Li** [comment]
https://github.com/Geeksltd/MSharp.Docs/blob/0ef32648ba269e927d518645aee8233a03528f49/index.html#L43-L46

This should be changed

```js
return editHtml
  + html
  + '\n\n----\n\n'
  + '<a href="https://docsify.js.org" target="_blank" style="color: inherit; font-weight: normal; text-decoration: none;">Powered by docsify</a>'
```
