### ISSUE TITLE
编辑完之后怎么更新缓存呢？

### ISSUE THREAD

**Issue by xwinstone** [QingWei-Li/docsify#418]
每次编辑完之后 都要清理浏览器缓存才能看到新的内容

**Comment by QingWei-Li** [comment]
如果部署在 GitHub Pages，资源请求的 `max-age` 是 `600`。所以十分钟后在进去就更新了

**Comment by xwinstone** [comment]
现在是部署在自己的服务器上， 所以要设置header的max-age才可以吗

**Comment by QingWei-Li** [comment]
Right

**Comment by xwinstone** [comment]
thanks
