### ISSUE TITLE
Sidebar button on top

### ISSUE THREAD

**Issue by mohsens22** [QingWei-Li/docsify#419]
Hello.
In current docsify release the sidebar button in the bottom of the screen. As long as this thing is not a UI trend, users can be confused. 
Is there any way to change the alignment to top?

**Comment by QingWei-Li** [comment]
Duplicate of #396

**Comment by soneji** [comment]
If anybody else is coming across this issue and can't find any solutions online I fixed it by adding this to a `<style>` block underneath all the existing `<link...` stylesheets

```html
<style>
    .sidebar-toggle {
      position: relative !important;
      top: 0 !important;
    }
</style>
```
