### ISSUE TITLE
A way to do search

### ISSUE THREAD

**Issue by luminarious** [QingWei-Li/docsify#43]
Needs a way to do search in sidebar, like Docute. One options is something like http://lunrjs.com

**Comment by QingWei-Li** [comment]
Actually, I considered doing search. I like docute implementation, but i dont think it is easy to use.

I have considered using GitHub search API, that we can easy doing seach, [such as](https://api.github.com/search/code?q=docsify+language:Markdown+path:docs+repo:QingWei-Li/docsify). But it has limitations.

> For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute.

Lunrjs looks good, but seems to only search the current page?

I have no other ideas.

**Comment by egoist** [comment]
For large website, I think it's worth putting effort to use docsearch from algolia, since it's really powerful.

For small-to-medium website, maybe a feature like gitbook's search? but it requires to build json

For small website, we may not need to search (๑˙ー˙๑)

---

And, what about private docs 😂

**Comment by yangyang0507** [comment]
How about [hexo-theme-next](https://github.com/iissnan/hexo-theme-next)'s localSearch, use [hexo-generator-search](https://www.npmjs.com/package/hexo-generator-search), it will generate a json file(db.json) to save searchinfo.  but this plugin base on hexo

**Comment by QingWei-Li** [comment]
@luminarious @egoist @yangyang0507 
The search is supported! Because I consider to be compatible with Chinese characters, I did not use `lunrjs`.


```html
<script src="//unpkg.com/docsify/lib/docsify.js"></script>
<script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
```



demo: https://docsify.js.org/

**Comment by BeamerIsHere** [comment]
I have added "<script src="//unpkg.com/docsify/lib/plugins/search.js"></script>" 
Search box is appered there but not working. Always giving 'No Result'.
Any suggestion..?

**Comment by mrsnax** [comment]
> I have added "<script src="//unpkg.com/docsify/lib/plugins/search.js"></script>"
> Search box is appered there but not working. Always giving 'No Result'.
> Any suggestion..?

same here, no results at all :(

**Comment by obernardovieira** [comment]
Within `<body>` there's a `<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>`, add `<script src="//unpkg.com/docsify/lib/plugins/search.js"></script>` after that. It worked for me.

**Comment by codingplayboy** [comment]
The search plugin is searching nested with nested sidebar, so must set:

```
window.$dcosify = {
  loadSidebar: true
};
```

And in default _sidebar.md, we need add the nested file:

```
* [Configuration](configuration/)
  * [Basic Configuration](configuration/basic)
// ...
```

**Comment by Jayxiang** [comment]
> I have added "<script src="//unpkg.com/docsify/lib/plugins/search.js"></script>"
> Search box is appered there but not working. Always giving 'No Result'.
> Any suggestion..?

same

**Comment by coolkit-carl** [comment]
Following the configuration of https://docsify.js.org/, my project search function works fine.

```
    search: {
        noData: {
          '/zh-cmn/': '没有结果!',
          '/en/': 'No results!'
        },
        paths: 'auto',
        placeholder: {
          '/zh-cmn/': 'Search',
          '/en/': 'Search'
        }
      },
```

**Comment by dipunj** [comment]
> I have added "<script src="//unpkg.com/docsify/lib/plugins/search.js"></script>"
> Search box is appered there but not working. Always giving 'No Result'.
> Any suggestion..?

It builds a search index in your localstorage, which might take a while to create.
