### ISSUE TITLE
Page does not open at the top when following a link 

### ISSUE THREAD

**Issue by dialex** [QingWei-Li/docsify#435]
**Steps to reproduce:**

1. Open a page.
2. Scroll down.
3. Open a new page.

**Expected:** The new page opens at the top.
**Actual:** The new page opens at the same scroll level of the previous page.

As a user reading the page and following a link to read more this is confusing, because the next page seems to open at a random spot. See the gif below:

![bug](https://user-images.githubusercontent.com/2140450/37874418-bbec6868-3026-11e8-9838-bb4cf90a51bf.gif)

You can view the website code [here](https://github.com/dialex/start-testing). This is my [index.html](https://github.com/dialex/start-testing/blob/master/docs/index.html). Check it [live here](https://dialex.github.io/start-testing/#/).

**Comment by surajmandalcell** [comment]
Same issue here, have to look for a workaround i guess

**Comment by surajmandalcell** [comment]
Thanks, i configured it and it works like a charm

**Comment by brendon** [comment]
Just a thought, wouldn't it be better for this to default to `true` instead of `false`? It seems (to me at least) that this would be the most commonly expected behaviour.
