### ISSUE TITLE
Auto-expanding sub headers

### ISSUE THREAD

**Issue by dmed256** [QingWei-Li/docsify#440]
Hi, thanks a ton for making this project!
I would like to auto-expand the sub headers without viewing that section (since my sidebar is pretty short).

If that feature would get approved, can you show me where the expansion happens for sub-headers?
I can try to submit a PR for it.

Not sure if it's here:
https://github.com/QingWei-Li/docsify/blob/master/src/core/fetch/index.js

Thanks!

**Comment by e-volusian** [comment]
David: I also have a smaller site and would like to have all the headers expanded at once. Did you figure out how to make this happen?

**Comment by e-volusian** [comment]
Ok. I ended up using your [libocca sidebar.md](https://raw.githubusercontent.com/libocca/libocca.org/master/guide/_sidebar.md) to do something similar
