### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by denvist** [QingWei-Li/docsify#45]
Links into a book page and into "aside" is not working.
You may watch this by [url](http://books.rdbcn.pw/#/zhikarentsev/doroga-domoy-doroga-domoy).

Latest version is used.

![screen shot 2016-12-30 at 21 44 19](https://cloud.githubusercontent.com/assets/7146527/21570667/47eca0e0-ced9-11e6-9ee5-fd02694866c2.png)

**Comment by QingWei-Li** [comment]
fixed in `1.4.1`

**Comment by denvist** [comment]
@QingWei-Li, yes now it's work. But 'aside' is now empty :)

**Comment by QingWei-Li** [comment]
If you do not use the custom sidebar, you should remove it.

![image](https://cloud.githubusercontent.com/assets/7565692/21576375/6afe75de-cf67-11e6-8430-e56c18a78ade.png)

`_sidebar.md` file not found.
![image](https://cloud.githubusercontent.com/assets/7565692/21576376/70eb089a-cf67-11e6-8e30-eb79b17d9946.png)

**Comment by denvist** [comment]
Yes, a saw this error in earlier version too.
On the top of the site i use custom sidebar, but inside the book i need toc.

**Comment by QingWei-Li** [comment]
I found a "new feature", create an empty sidebar.md in `zhikarentsev/` and it will work. 😂
