### ISSUE TITLE
Broken markdown links with query string

### ISSUE THREAD

**Issue by jhildenbiddle** [QingWei-Li/docsify#453]
Docisfy is escaping the query string `?`, resulting in broken markdown links.

Example: https://docsify.js.org/#/quickstart?id=initialize

```markdown
[Quick Start - Initialize](https://docsify.js.org/#/quickstart?id=initialize)
```

When that markdown link is clicked, the following URL sent to the browser: `https://docsify.js.org/#/quickstart%3Fid=initialize`.

**Comment by SidVal** [comment]
I have this situation (linking to `?` inside a doc) and works fine right now. 

Can you check @jhildenbiddle  ?
