### ISSUE TITLE
建议添加rss支持

### ISSUE THREAD

**Issue by aiokr** [QingWei-Li/docsify#456]
建议支持通过rss输出文档

**Comment by QingWei-Li** [comment]
没理解你的意思，可否详细举个例子？

**Comment by aiokr** [comment]
emm，很抱歉我在提出此issue时没有注意到rss的文件格式与文档不大一致。
我的意思是希望能够在生成文档的同时，生成一个xml文件或json文件，方便app或是其他网页引用文档的内容。

**Comment by QingWei-Li** [comment]
不考虑，涉及到静态编译的特性都不考虑。
