### ISSUE TITLE
Navbar didin't work?

### ISSUE THREAD

**Issue by MikeMaldini** [QingWei-Li/docsify#461]
It's my folder：

![image](https://user-images.githubusercontent.com/29230494/38849841-0da92afc-4241-11e8-91eb-10dddcfac443.png)

And it didn't show `abc` Navbar

![image](https://user-images.githubusercontent.com/29230494/38849872-47f1affe-4241-11e8-8acb-874e9bdef4ed.png)

**Comment by jhildenbiddle** [comment]
The `docsify-copy-code` plugin was recently updated to v2 which changes how you add the plugin to your site. The summary is:

1. You no longer need to `<link>` to an external stylesheet (styles are bundles in the JS)
1. You no longer need to manually initialize the plugin using `window.DocsifyCopyCodePlugin.init()`. Remove this call to avoid a JS error.
1. The `<script>` href has changed. See updated instructions in the repo [README](https://github.com/jperasmus/docsify-copy-code).
