### ISSUE TITLE
Search results link

### ISSUE THREAD

**Issue by zimbozambo** [QingWei-Li/docsify#463]
When using the search results link, if I have changed the location of a file, when I search for a keyword within that particular file, the search result link is the old link that doesn't exist anymore:

**Folders**

- getting-started / intro.md

This used to be:
- quick-start / test.md
and the search links to:
![image](https://user-images.githubusercontent.com/23533321/38879857-3a70153a-425c-11e8-89d9-81ad73b52fa2.png)

Is there a way to clear the cache or similar?

**Comment by dmed256** [comment]
Search information in stored in `Local Storage`. You'll have to clear it to see the updated changes.

![local_storage](https://user-images.githubusercontent.com/1812355/39414780-28137770-4c01-11e8-9f56-4cf71d8aea85.png)
