### ISSUE TITLE
在此项目下添加的文件，部署后生成下载链接，但访问显示404

### ISSUE THREAD

**Issue by Tusiji** [QingWei-Li/docsify#472]
https://help.aryun.com/#/assets/design/ARKankanDesign.psd
此链接为自动生成的，点击后显示404页面

https://help.aryun.com/assets/design/ARKankanDesign.psd
链接去掉“#”之后，可以正常下载

请问如何解决这个问题？

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/configuration?id=nocompilelinks
