### ISSUE TITLE
[enhance proposal] auto create sidebar by using github open repo api

### ISSUE THREAD

**Issue by xinmu99** [QingWei-Li/docsify#474]
建议添加 可以 直接通过  [调用github开放api获取repo文件夹结构] 自动生成sidebar导航栏 功能

auto create sidebar by using github open repo api

https://api.github.com/repos/QingWei-Li/docsify/git/trees/master?recursive=1&_=1524995079227

**Comment by QingWei-Li** [comment]
docsify 不是为 GitHub 设计的

**Comment by xinmu99** [comment]
好吧。自己写了插件 https://github.com/xinmu99/docDirTreeToMd
