### ISSUE TITLE
Live Previewing docsify in Brackets doesn't work

### ISSUE THREAD

**Issue by ItsPugle** [QingWei-Li/docsify#477]
I'm not sure if this is something for [`@adode/brackets`](https://github.com/adobe/brackets) or not, but if you use the Live Preview feature in Brackets on a Docsify site, it doesn't load properly:
![Error](https://rpl.cat/uploads/6xdIBDkJAhmFC8MM_Q089kR5D4D_qjMBdobyGh2fwiw/public.png)

**Comment by dmed256** [comment]
It could be the extra `/index.html` is messing up the loading since it expects:

- `/#/hi` -> `./hi.md`
- `/#/hi/` -> `./hi/README.md`

What network calls do you see made when you hit that url?
For example:

![ss](https://user-images.githubusercontent.com/1812355/39664138-8642866e-5044-11e8-94fc-064e42ce46e9.png)

**Comment by ItsPugle** [comment]
It's coming back and saying that it can't find directories for the files (?). I mean, it's more a quirk then an issue right now since I can just use `$ docsify serve .`
![untitled](https://user-images.githubusercontent.com/22669894/39668825-d25193be-511c-11e8-8b47-9f2f16f7409b.png)

**Comment by dmed256** [comment]
I was able to replicate that same issue
![ss1](https://user-images.githubusercontent.com/1812355/39670365-bd737f74-50c8-11e8-9cdf-49d234332e72.png)
removing the `index.html` part seemed to make it work :)
![ss2](https://user-images.githubusercontent.com/1812355/39670368-c6af5a54-50c8-11e8-9613-d51eee17e43d.png)
Hope it helps!

**Comment by ItsPugle** [comment]
Ah, yes! You're right - it's working. I wonder if it's anyways to get this going automatically without having to change the URL 😄

**Comment by dmed256** [comment]
Oh, seems that `location.hash` is the same even with `index.html` in front of it

![hash](https://user-images.githubusercontent.com/1812355/39675042-fa95e174-511a-11e8-90dd-93d60d704acf.png)

I'll try to fix it

**Comment by ItsPugle** [comment]
That's a good find 😄 I'm happy to use that workaround! Thanks for the help.
