### ISSUE TITLE
内容解析

### ISSUE THREAD

**Issue by gavinliu6** [QingWei-Li/docsify#480]
当我的文档内容是这样的时：
![tim 20180511152648](https://user-images.githubusercontent.com/29831211/39912027-db4b5290-552f-11e8-9c44-acfff92be186.png)
浏览器就会报如下错误：
![tim 20180511152853](https://user-images.githubusercontent.com/29831211/39912071-11150970-5530-11e8-8a33-9eb571b67404.png)
@QingWei-Li

**Comment by gavinliu6** [comment]
好像只在代码语言是php时才会这样

**Comment by dmed256** [comment]
Can you add this to your `index.html` file?

```html
    <script src="//unpkg.com/prismjs@1.13.0/components/prism-php.min.js"></script>
```

**Comment by gavinliu6** [comment]
I did not unstant what you mead, my `index.html` is like this:
`<script src="//unpkg.com/prismjs/components/prism-php.js"></script>`

**Comment by dmed256** [comment]
🤔 hmm strange
I looked at it again and it fails when tokenizing `${foo}` (called _interpolation_ by marked)

![error](https://user-images.githubusercontent.com/1812355/39975788-a4f17820-56fe-11e8-95ce-90b4c69d9e4c.png)

I'm seeing `language = undefined` even though I have

```md
| ```php
| $str = "{$a}";
| ```
```

I'll look into it a bit more

**Comment by dmed256** [comment]
This works

```md
| ```cpp
| $str = "{$a}";
| ```
```

Maybe because C++ doesn't have _interpolating_ tokens

**Comment by gavinliu6** [comment]
All right! If you solve the problem, please tell me. Thank you!

**Comment by dmed256** [comment]
@gavinliu6 Can you try an older version of prismjs? 

```html
    <script src="//unpkg.com/prismjs@1.9.0/components/prism-php.min.js"></script>
```

Docsify comes with 1.9.0 and I think we're both picking up 1.13.0 which fails

**Comment by gavinliu6** [comment]
Great, that works! Thank you very much for your help.
