### ISSUE TITLE
左侧菜单栏出现莫名的"-Summary"子节点，且影响右侧内容显示

### ISSUE THREAD

**Issue by jintaixizhao** [QingWei-Li/docsify#492]
![image](https://user-images.githubusercontent.com/17608083/40214934-40d35058-5a90-11e8-80fa-1d594d42fb0f.png)
菜单栏如上，出现莫名的"-Summary"子节点，如果不出现这个子节点，那么右侧的mermaid流程图一直出不来。
只有点击某个菜单后，刷新，才会出现这个子节点。
不知道什么原因。

**Comment by dmed256** [comment]
@jintaixizhao Do you have a link to the source code?

**Comment by jintaixizhao** [comment]
抱歉，那个-Summary子节点，原因是_sidebar.md中存在这样的一个标题，删除了之后就正常了。
同一菜单栏出现只有一个子节点点击后能完整展示流程图的情况，应该是我的docsify配置出了问题，修改了之后，就好了。
