### ISSUE TITLE
Russian Language

### ISSUE THREAD

**Issue by truepatch** [QingWei-Li/docsify#498]
My repo https://github.com/truepatch/docsify-ru
Translated Pages https://docsify-ru.js.org/

**Comment by QingWei-Li** [comment]
Done https://github.com/QingWei-Li/docsify/blob/master/docs/_navbar.md

**Comment by jrappen** [comment]
@truepatch 

* Why not send a pull request to include the Russian docs into the main repo?
* Could you update the Russian docs?

**Comment by QingWei-Li** [comment]
@jrappen @truepatch @SidVal 
Hi all,
I'm glad you can provide your own language translation. Before I considered this is inconvenient to maintain if all docs are under the same repo, so I propose that you build your own website. Now, I have already translated all non-English translations into independent repos (https://github.com/docsifyjs/docs-zh and https://github.com/docsifyjs/docs-de). I will invite you to join the organization and maintain them together. 🤗

**Comment by jrappen** [comment]
@QingWei-Li Could you add a LICENSE file to them? By the way, you can add your name and email address into the header line as `QingWei Li <cinwell.li@gmail.com>`. That seems like a standard way to do it.

**Comment by jrappen** [comment]
Also:

* please add us as admins to the relevant repos
* I added a @docsifyjs/translators team
