### ISSUE TITLE
Cover custom color only works for hex/name

### ISSUE THREAD

**Issue by citycide** [QingWei-Li/docsify#52]
You give an example of using a CSS `linear-gradient` as a custom background on the cover in https://github.com/QingWei-Li/docsify/issues/40#issuecomment-269345713. But this doesn't work for me, I can only get simple hex or name (`green`) values to work.

This line copied directly from your comment doesn't work when placed in `cover.md`:

`![color](linear-gradient(to left bottom, #b3ffc8 0%, #eeffb3 100%))`

**Comment by pdao1** [comment]
same.  my workaround was just to edit the css directly.

	.cover.show {
background: linear-gradient(to left top, #821617 0%, #B31F29 20%, #FEC443 100%) !important;
		}
