### ISSUE TITLE
<hr> support

### ISSUE THREAD

**Issue by noclat** [QingWei-Li/docsify#54]
Hey,

Thanks for bringing Docsify, it's awesome! I just noticed it lacks of `<hr>` styling, could you make that possible?

---

Here the [Markdown horizontal rule specs](https://daringfireball.net/projects/markdown/syntax#hr).

**Comment by QingWei-Li** [comment]
fixed via https://github.com/QingWei-Li/docsify/pull/55/commits/1d776670df0bd474d3e2cb35502a2f0a209484bd

**Comment by noclat** [comment]
Thanks! A margin-bottom would help though… :). #sorry
