### ISSUE TITLE
希望支持markdown中文换行。

### ISSUE THREAD

**Issue by hifizz** [QingWei-Li/docsify#60]
在markdown的语法中，只要是英文开头的一行，按下回车之后，解析出来的html也会换行；但如果是中文开头的话，按回车换行解析出来还是会在同一行。按两次回车才会开始下一段落。这也是很多markdown编辑器不好用的一个点：英文可以自由换行，但中文就不行，还美其名曰markdown本身语法就是这样。不知作者能不能支持这个换行功能呢？

**Comment by QingWei-Li** [comment]
这不是这里能做的 😂 内置的是 marked 你可以去它的仓库里提 issue

**Comment by hifizz** [comment]
@QingWei-Li ...... 好吧

**Comment by nimojs** [comment]
```js
marked('离离原  \n上草，一岁一枯荣。野火烧不尽，春风吹又生。远芳侵古道，晴翠接荒城。又送王孙去，萋萋满别情。')
```
```html
<p>离离原<br>上草，一岁一枯荣。野火烧不尽，春风吹又生。远芳侵古道，晴翠接荒城。又送王孙去，萋萋满别情。</p>
```

这样写
```js
中文一二三{空白符}{空白符}
第二行文字
```

**Comment by hifizz** [comment]
@nimojs 卧槽还有这样的黑科技。。。这样确实满足了我的要求。

**Comment by nimojs** [comment]
@hifizz 
marked 的配置项也挺多的，你可以看看。基本上能满足大部分的书写需求。不能满足的就找类似 markrun 这样的增强插件

**Comment by egoist** [comment]
其实你也可以直接写 `<br>` 😂

**Comment by egoist** [comment]
```bash
> require('marked')('我爱\n你')
'<p>我爱\n你</p>\n'
> require('marked')('我爱\n你', {breaks:true})
'<p>我爱<br>你</p>\n'
```
