### ISSUE TITLE
Search on a mobile browser

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#67]
Glad to see the search plugin! 👍 
But there is a bug when I test it on a mobile browser (at least on Firefox for Android). When I click on the search bar, the sidebar will hide itself...

Another problem is that `data-auto2top` has no effect on a mobile browser.

**Comment by QingWei-Li** [comment]
`auto2top`  is work in iPhone Safari/Chrome. I don't have Android devices to test...

**Comment by liulex** [comment]
No problem on Chrome for Android too. Try Firefox for iOS, maybe?
