### ISSUE TITLE
Why use 404.html instead of index.html

### ISSUE THREAD

**Issue by DIYgod** [QingWei-Li/docsify#7]
I try rename 404.html to index.html, it works well, see: http://dplayer.js.org/docs/

Using 404 has two defect:

- Can't put docs to second-level directory
- Not SEO friendly

**Comment by QingWei-Li** [comment]
Of course, It's works. If it is a multi-level directory, it will not work. Such as `/first/second`, the `first/second.html` is not exist.

If the server can't find the file, it will fallback to `404.html`

**Comment by DIYgod** [comment]
So, why not use index.html....

**Comment by QingWei-Li** [comment]
GitHub Pages not support history api fallback. But the url can not be found, the `404.html` will be rendered. This `first/second.html` actually does not exist, but it can be rendered dynamically if it fallback to `404.html`. Sorry for my bad english. 😅

**Comment by DIYgod** [comment]
还是用中文吧...

我知道用 `404.html` 是可行的，但为什么不用 `index.html`，想问下这样做的原因是什么？

比如我有个项目`DPlayer`，dplayer.js.org 一级目录用来做demo页了，然后想在 dplayer.js.org/docs 二级目录做文档页面，如果是 `404.html` 就无法实现了，只改成 `index.html`

**Comment by MCBBC** [comment]
HI ! Man DIYgod is FuTa

**Comment by QingWei-Li** [comment]
index.html 可行，如果你只有一个文档的话，但是多个文档文件就没办法了。比如说我有这样的结构
```
-| README.md
-| zh-cn.md
```

其中 `README.md` 是主页面，我可以直接通过 `domain.com` 访问。但是要访问 `domain.com/zh-cn` 就会找不到文件，因为并不存在一个叫 `zh-cn.html` 的文件，所以就会 fallback 到 `404.html`。我只是利用了可自定义 404 的特性实现了 "SPA" 的效果

**Comment by DIYgod** [comment]
奇巧淫技，学到了！

**Comment by QingWei-Li** [comment]
至于你说的 SEO，因为内容是动态生成的，似乎没办法做到 😅

**Comment by DIYgod** [comment]
只是感觉一直返回的是404不太友好... 但这样的好处也很明显...

**Comment by QingWei-Li** [comment]
好的 我会在文档里提一下，如果只是单页文档就直接用 index.html

**Comment by egoist** [comment]
Since it's always SEO-unfriendly, I think hash routing is fine for both cases (multi-pages and using index.html), maybe add an option for using hash routing?

**Comment by citycide** [comment]
I don't really understand what kind of workflow is supposed to come out of this. If I call my file `404.html`, GitHub uses `README.md` as the index. If I call it `index.html`, `docsify serve docs` fails saying there's no `404.html` - so I can't even use the dev server. Am I not understanding something here?

**Comment by QingWei-Li** [comment]
@citycide `docsify-cli` bug, fixed in `1.1.0`, please upgrade `docsify-cli`. 😁

**Comment by egoist** [comment]
@citycide by the way, you can use `.nojekyll` to prevent from serving README.md as index

**Comment by citycide** [comment]
@QingWei-Li nicely done, I'm glad I wasn't doing anything glaringly wrong! @egoist thanks for that tip also.
