### ISSUE TITLE
搜索功能localstorage的更新

### ISSUE THREAD

**Issue by LancelotLewis** [QingWei-Li/docsify#71]
貌似在设置完搜索功能之后，需要更新搜索文档列表的时候必须手动删除localstorage才行，建议加一个key保存之前搜索文档的`paths`，检测到paths更新的时候自动更新一下localstorage里面的`index`

**Comment by yangyang0507** [comment]
超时时间自己设置啊~ 默认一天的嘛

**Comment by QingWei-Li** [comment]
设置默认过期时间 `maxAge` 就好了
