### ISSUE TITLE
Auto-expand sidebar

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#79]
What do I need to do to make the titles in sidebar auto expand when clicked, like https://docsify.js.org? 😄

**Comment by QingWei-Li** [comment]
https://docsify.js.org/#/zh-cn/configuration#max-level

For example

```html
<script
  src="//unpkg.com/docsify"
  data-repo="QingWei-Li/docsify"
  data-max-level="3"
  data-coverpage>
</script>
```

Thank you for your money. ❤️

**Comment by liulex** [comment]
Oh, I didn't notice that option. 😅 
Thanks!
