### ISSUE TITLE
some items in sidebar highlight incorrectly.

### ISSUE THREAD

**Issue by reverland** [QingWei-Li/docsify#86]
check https://docsify.js.org/#/cdn?id=other-cdn
click other-cdn, it won't be highlighted.

it is because sidebar highlight is computed from scroll position, but several headers in the last will never appear on top of viewport

**Comment by reverland** [comment]
why not `getAndActive(sidebar, true, true)` when `isMobile` is false?

**Comment by QingWei-Li** [comment]
The sidebar is hidden by default on the mobile. No need to scroll when the highlight.

**Comment by reverland** [comment]
no, I mean even if its not in mobiles, getAndActive should be perform?

**Comment by QingWei-Li** [comment]
Actually I just check the viewport less than 600px as a mobile.

**Comment by reverland** [comment]
大佬orz，

我英文不好，就是想问不在viewport大于600px时getAndActive有什么考虑么

**Comment by QingWei-Li** [comment]
getAndActive 不是在非移动设备上才执行了 难道我写反了？
![image](https://cloud.githubusercontent.com/assets/7565692/23121235/961ae710-f79a-11e6-88d6-a0bbfc5359f7.png)
