### ISSUE TITLE
Can we support custom navbar in sub folder?

### ISSUE THREAD

**Issue by yangyang0507** [QingWei-Li/docsify#87]
Just a piece of advice

When we hava a custom navbar md file in sub folder,  then we can render differenet  *_navbar.md* to support i18n page, just like sidebar

**Comment by QingWei-Li** [comment]
Yes, you can. https://docsify.js.org/#/zh-cn/custom-navbar?id=%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6

**Comment by yangyang0507** [comment]
tks
