### ISSUE TITLE
Support links to be opened in another tab

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#9]
Sometimes we need some of the links to be opened in another browser tab, i.e. with `target="_blank"`.

**Comment by QingWei-Li** [comment]
Which links?

**Comment by liulex** [comment]
For example, it's better to open links like `[Issues](https://github.com/QingWei-Li/docsify/issues)` in a new tab, so that the documention site is not replaced.

In the content, we are able to do this by using html:
```html
<a href="https://github.com/QingWei-Li/docsify/issues" target="_blank">Issues</a>
```
~~But in the `_sidebar.md`, we cannot do this.~~

Oops, I just find out that in `_sidebar.md`, such code is also supported: :+1: 
```
  - <a href="https://github.com/QingWei-Li/docsify/issues" target="_blank">Issues</a>
```
 I guess I have no problem then. :smiley:
