### ISSUE TITLE
Docsify mounted in Jekyll

### ISSUE THREAD

**Issue by GarPit** [QingWei-Li/docsify#95]
Hello, thank you for awesome library!

I have one problem. I have docsify mounted at /docs in Jekyll site. Everything is good except cases when I want to highlight Liquid (or Handlebars similar code):

    ```handlebars
    <nav role="navigation">
       <ul>
         {% for p in: index.children.find_all_by(hidden: false published: true) do: %}

Jekyll considers this as `for` tag (and throws error) but I need to display it as is. Do you have a workaround for this?

Liquid {% raw %} helps... but it outputs itself too :smile:

**Comment by QingWei-Li** [comment]
You can create a `.nojekyll` in your `/docs` folder.

**Comment by GarPit** [comment]
Yes, but it doesn't help :-(

**Comment by QingWei-Li** [comment]
https://github.com/webgradus/kms_site

Would you choose to deploy the master branch? If so, you should create .nojekyll in your root https://github.com/blog/572-bypassing-jekyll-on-github-pages , but you can not use jekyll. I suggest you create another repo to deploy your documentation site.

**Comment by GarPit** [comment]
So there's no solution to have both in one repo, right?

**Comment by QingWei-Li** [comment]
Yes, I think so.

**Comment by GarPit** [comment]
Ok, thank you. Will close it
