### ISSUE TITLE
可否支持一下 MathJax？

### ISSUE THREAD

**Issue by 40huo** [QingWei-Li/docsify#96]
加载 MathJax 代码后在公式页刷新是有效果的，但是从别的页面点进去就失效了，应该是没有回调？小白不太会弄。。。

**Comment by reverland** [comment]
mathjax啊，我也比较感兴趣

http://docs.mathjax.org/en/latest/api/hub.html#Rerender 因为路由变化时候要rerender下。你可以写个插件做这个

我更喜欢 https://github.com/Khan/KaTeX

**Comment by reverland** [comment]
可选的，可以像我在https://github.com/reverland/vud3/blob/master/docs/index.html#L32 里做的一样mogai markdown语法。。

**Comment by reverland** [comment]
另外，楼主做安全啊

**Comment by QingWei-Li** [comment]
简单的给个插件的写法吧，应该能满足你的需求（别忘了引入样式）
```html
<script>
  window.$docsify = {
    plugins: [
      function (hook) {
        hook.beforeEach(function (content) {
          return content.replace(/\$\$([\s\S]*?)\$\$/g, function (m, code) {
            return katex.renderToString(code)
          })
        })
      }
    ]
  }
</script>
<script src="//unpkg.com/katex/dist/katex.min.js"></script>
<script src="//unpkg.com/docsify"></script>
```

**Comment by reverland** [comment]
大佬快点去写浏览器端的webpack

**Comment by 40huo** [comment]
```html
<script>
window.$docsify = {
    plugins: [
      function (hook) {
        hook.beforeEach(function (content) {
          return content.replace(/\$\$([\s\S]*?)\$\$/g, function (m, code) {
            MathJax.Hub.Queue(["Typeset",MathJax.Hub])
          })
        })
      }
    ]
}
</script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true
    },
    "HTML-CSS": { availableFonts: ["TeX"] }
  });
</script>
<script src="//cdn.bootcss.com/mathjax/2.6.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```
我改成这样以后被单个$包围的可以渲染了，然而$$的却不行。。。
```markdown
# 测试例子

$
f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi
$
```
感觉是 `return` 的那部分要改改？
@reverland 正在学习安全，还是个菜鸡。。

**Comment by 40huo** [comment]
```javascript
  plugins: [
    function (hook) {
      hook.doneEach(function () {
        // 每次路由切换时数据全部加载完成后调用，没有参数。
        // ...
        if (typeof MathJax !== 'undefined') {
          MathJax.Hub.Queue(["Typeset", MathJax.Hub])
        }
      })
    }
  ]
```
已解决。

**Comment by jrappen** [comment]
Maybe this info could be added to the docs?

**Comment by jrappen** [comment]
The solution for Katex above does not work.

**Comment by QingWei-Li** [comment]
@jrappen 
Sorry, I will not use Katex. I just copied an expression, it is working for me.

```markdown
# Test

$$
f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi
$$
```

![image](https://cloud.githubusercontent.com/assets/7565692/23613079/e35fec40-02b8-11e7-9fb5-16a7da6c32a3.png)

```js
plugins: [
      function (hook) {
        hook.beforeEach(function (content) {
          return content.replace(/\$\$([\s\S]*?)\$\$/g, function (m, code) {
            console.log(code)
            return katex.renderToString(code.trim())
          })
        })
      }
    ]
```

**Comment by jrappen** [comment]
@QingWei-Li Not working for me, minimal example:

* <https://github.com/jrappen/test/blob/master/docs/index.html>
* <https://github.com/jrappen/test/blob/master/docs/README.md>
* <https://jrappen.github.io/test>

Am I doing something wrong?

**Comment by QingWei-Li** [comment]
@jrappen  Make sure katex is loaded before docsify.
```html
<script src="//unpkg.com/katex/dist/katex.min.js"></script>
<script src="//unpkg.com/docsify"></script>
<script src="//unpkg.com/docsify/lib/plugins/emoji.min.js"></script>
<script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>
</html>
```

**Comment by jrappen** [comment]
@QingWei-Li Ok, thanks.

**Comment by iolaizola** [comment]
I faced many issues with the proposed solutions. My main problem is that the subscript symol '_' is parsed as `<em>'. Therefore I wrote a workaround by replacing '_' before parsing and replacing it back after markdown parsing. I tested it with mathjax and works perfectly. I only included the $ and $$ symbols but could be easily extended to '\\[" like tags by copy-pasting the rules.

```javascript
        function (hook) {
          hook.beforeEach(function (content) {
            return content.replace(/\$\$([\s\S]*?)\$\$/g,
               function(x){ return x.replace('_','[subscript]')}
            )
          })
          hook.beforeEach(function (content) {
            return content.replace(/\$([\s\S]*?)\$/g,
               function(x){ return x.replace('_','[subscript]')}
            )
          })
          hook.afterEach(function(html, next) {
            html = html.replace(/\$\$([\s\S]*?)\$\$/g,
               function(x){ return x.replace('[subscript]','_') }
            )
            html = html.replace(/\$([\s\S]*?)\$/g,
               function(x){ return x.replace('[subscript]','_') }
            )
            next(html)
          })
        }
      ]

}

```

**Comment by pangann** [comment]
render $$\sum_i w_{jk}$$ error @40huo 
but can do with $$\sum\_i w_{jk}$$ correct.

**Comment by upupming** [comment]
Hi, I have created a new project for writing math on docsify.

This is my repo: https://github.com/upupming/docsify-katex

If you find any problems, please let me know!

**Comment by tmt514** [comment]
> I faced many issues with the proposed solutions. My main problem is that the subscript symol `'_'` is parsed as `<em>`. Therefore I wrote a workaround by replacing `'_'` before parsing and replacing it back after markdown parsing. I tested it with mathjax and works perfectly. I only included the $ and $$ symbols but could be easily extended to '\[" like tags by copy-pasting the rules.
> 
> ```js
>       plugins: [
>         function (hook) {
>           hook.beforeEach(function (content) {
>             return content.replace(/\$\$([\s\S]*?)\$\$/g,
>                function(x){ return x.replace(/[_]/g,'[subscript]')}
>             )
>           })
>           hook.beforeEach(function (content) {
>             return content.replace(/\$([\s\S]*?)\$/g,
>                function(x){ return x.replace('_','[subscript]')}
>             )
>           })
>           hook.afterEach(function(html, next) {
>             html = html.replace(/\$\$([\s\S]*?)\$\$/g,
>                function(x){ return x.replace(/(\[subscript\])/g,'_') }
>             )
>             html = html.replace(/\$([\s\S]*?)\$/g,
>                function(x){ return x.replace(/(\[subscript\])/g,'_')}
>             )
>             MathJax.Hub.Queue( ["Typeset",MathJax.Hub] ) // calling it twice
>             MathJax.Hub.Queue( ["Typeset",MathJax.Hub] ) //fixes MathJax refresh issue
>             next(html)
>           })
>         }
>       ]
> ```

Just a comment here: I used MathJax3 and it worked with `MathJax.typeset()` inside the `hook.doneEach()` perfectly!

**Comment by scruel** [comment]
Mathjex V3 版本配置设置：
局部刷新配置方式，直接在 `plugins` 中配置：
```
  <script>
    window.$docsify = {
      ...

      plugins: [
        function(hook, vm) {
          hook.doneEach(function(html, next) {
            MathJax.config.tex.inlineMath = [['$', '$']];
            MathJax.config.tex.displayMath = [['$$', '$$']];
            MathJax.startup.getComponents();
            MathJax.typeset();
          });
        }
      ]
    }
  </script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

（推荐）全局预配置方式：
```
  <script>
    window.$docsify = {
      ...

      plugins: [
        function(hook, vm) {
          hook.doneEach(function(html, next) {
            MathJax.typeset();
          });
        }
      ]
    }
  </script>
  <script>
  MathJax = {
    tex: {
      inlineMath: [['$', '$']],
      displayMath: [ ['$$', '$$']]
    }
  };
  </script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by scruel** [comment]
随手写了个：
github.com/scruel/docsify-latex
简单引用就行了：
```最新
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsify-latex@latest"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by scruel** [comment]
随手写了个：
https://github.com/scruel/docsify-latex
简单引用就行了：
```最新
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsify-latex@latest"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by scruel** [comment]
https://github.com/scruel/docsify-latex
You can use this plugin with MathJax and KaTeX.
