### ISSUE TITLE
是否支持直接从文档根目录根据目录层级关系生成sidebar？

### ISSUE THREAD

**Issue by ruter** [QingWei-Li/docsify#98]
感谢开发出这么棒的工具！

在查看了很多次文档以及亲自使用之后，发现sidebar定制需要手动编辑`_sidebar.md`文件自己指定链接，后续更新能否考虑加入一个插件，自动遍历目录下的所有目录层级关系，以文件夹为目录顶级，以目录下的`.md`文档为二级目录？

**Comment by QingWei-Li** [comment]
由于所有渲染操作都是动态的，没办法自动获取目录列表。况且列表的顺序也无法保证。GitBook 虽然是静态编译的工具，但也是需要手动建立目录列表的。所以不打算支持这功能。

**Comment by ruter** [comment]
Thanks! 了解了ww
