### ISSUE TITLE
Per-sidebar name link

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#99]
Since the name link is placed in the sidebar, it would be nice to be able to speficify different name links on different sidebars. For example:

```js
window.$docsify = {
  nameLink: {'/': '/', '/zh-cn/': '/zh-cn/'}
}
```

**Comment by QingWei-Li** [comment]
SEO 似乎正常了。。。
![image](https://cloud.githubusercontent.com/assets/7565692/23289623/0b46cb4c-fa86-11e6-96dd-6d48acf98a84.png)

**Comment by liulex** [comment]
为什么会选到中间那句。。😂 

另外，我在 Nginx 里将 https://docs.snipaste.com/zh-cn 重定向到 https://docs.snipaste.com/#/zh-cn 了，有没有办法让 https://docs.snipaste.com/zh-cn 被搜索引擎收录到？
![default](https://cloud.githubusercontent.com/assets/2010459/23289804/3e3b6b38-fa87-11e6-8631-861a308b79a5.png)

**Comment by QingWei-Li** [comment]
我一直觉得 Google 爬 SPA 的逻辑很迷。。你试试把 `index.html` 里导航的链接改成

```html
<nav style="position: fixed;">
    <a href="/">En</a>
    <a href="/zh-cn/">中文</a>
  </nav>
```

然后过段时间再试试

**Comment by liulex** [comment]
好的~

**Comment by liulex** [comment]
`nameLink` 本地化似乎没有效果 😂
[test here](https://docs.snipaste.com/#/zh-cn/)
[index.html](https://github.com/liulex/Snipaste-Feedback/blob/master/docs/index.html)

**Comment by QingWei-Li** [comment]
顺序反了

**Comment by liulex** [comment]
😂 Thanks~
